services:
  monorepo_dev:
    environment:
      - NODE_ENV=development

    container_name: nestjs-remix-monorepo-dev
    build:
      context: .
      dockerfile: Dockerfile
      # image: massdoc/nestjs-remix-monorepo:dev

    restart: always
    ports:
      - "3000:3000"