export const ErrorCodes = {
  AUTH: {
    UNAUTHENTICATED: 'AUTH.UNAUTHENTICATED',
    FORBIDDEN: 'AUTH.FORBIDDEN',
    INVALID_CREDENTIALS: 'AUTH.INVALID_CREDENTIALS',
    SESSION_EXPIRED: 'AUTH.SESSION_EXPIRED',
    TOKEN_INVALID: 'AUTH.TOKEN_INVALID',
    TOKEN_EXPIRED: 'AUTH.TOKEN_EXPIRED',
  },

  VALIDATION: {
    FAILED: 'VALIDATION.FAILED',
    INVALID_FORMAT: 'VALIDATION.INVALID_FORMAT',
    REQUIRED_FIELD: 'VALIDATION.REQUIRED_FIELD',
    INVALID_EMAIL: 'VALIDATION.INVALID_EMAIL',
    INVALID_RANGE: 'VALIDATION.INVALID_RANGE',
  },

  PAYMENT: {
    INVALID_AMOUNT: 'PAYMENT.INVALID_AMOUNT',
    GATEWAY_ERROR: 'PAYMENT.GATEWAY_ERROR',
    GATEWAY_TIMEOUT: 'PAYMENT.GATEWAY_TIMEOUT',
    SIGNATURE_MISMATCH: 'PAYMENT.SIGNATURE_MISMATCH',
    CREATE_FAILED: 'PAYMENT.CREATE_FAILED',
    NOT_FOUND: 'PAYMENT.NOT_FOUND',
    UPDATE_FAILED: 'PAYMENT.UPDATE_FAILED',
    REFUND_INVALID: 'PAYMENT.REFUND_INVALID',
    CONFIG_MISSING: 'PAYMENT.CONFIG_MISSING',
  },

  CATALOG: {
    PRODUCT_NOT_FOUND: 'CATALOG.PRODUCT_NOT_FOUND',
    GAMME_NOT_FOUND: 'CATALOG.GAMME_NOT_FOUND',
    FAMILY_NOT_FOUND: 'CATALOG.FAMILY_NOT_FOUND',
    INVALID_TYPE_ID: 'CATALOG.INVALID_TYPE_ID',
    INVALID_PG_ID: 'CATALOG.INVALID_PG_ID',
    RPC_FAILED: 'CATALOG.RPC_FAILED',
    STATS_FAILED: 'CATALOG.STATS_FAILED',
  },

  CART: {
    EMPTY: 'CART.EMPTY',
    PRODUCT_NOT_FOUND: 'CART.PRODUCT_NOT_FOUND',
    ITEM_NOT_FOUND: 'CART.ITEM_NOT_FOUND',
    UPDATE_FAILED: 'CART.UPDATE_FAILED',
  },

  ORDER: {
    NOT_FOUND: 'ORDER.NOT_FOUND',
    ARCHIVE_FAILED: 'ORDER.ARCHIVE_FAILED',
    RESTORE_FAILED: 'ORDER.RESTORE_FAILED',
    CALCULATION_FAILED: 'ORDER.CALCULATION_FAILED',
    DELETE_FAILED: 'ORDER.DELETE_FAILED',
  },

  USER: {
    NOT_FOUND: 'USER.NOT_FOUND',
    DUPLICATE_EMAIL: 'USER.DUPLICATE_EMAIL',
    PASSWORD_FAILED: 'USER.PASSWORD_FAILED',
    RESET_TOKEN_FAILED: 'USER.RESET_TOKEN_FAILED',
    NOT_IMPLEMENTED: 'USER.NOT_IMPLEMENTED',
  },

  SUPPORT: {
    QUOTE_NOT_FOUND: 'SUPPORT.QUOTE_NOT_FOUND',
    QUOTE_NOT_SENT: 'SUPPORT.QUOTE_NOT_SENT',
    QUOTE_EXPIRED: 'SUPPORT.QUOTE_EXPIRED',
    CLAIM_NOT_FOUND: 'SUPPORT.CLAIM_NOT_FOUND',
    CLAIM_INVALID_STATE: 'SUPPORT.CLAIM_INVALID_STATE',
    FAQ_NOT_FOUND: 'SUPPORT.FAQ_NOT_FOUND',
    FAQ_CATEGORY_NOT_FOUND: 'SUPPORT.FAQ_CATEGORY_NOT_FOUND',
    FAQ_CATEGORY_HAS_ITEMS: 'SUPPORT.FAQ_CATEGORY_HAS_ITEMS',
    FAQ_CATEGORY_EXISTS: 'SUPPORT.FAQ_CATEGORY_EXISTS',
    REVIEW_NOT_FOUND: 'SUPPORT.REVIEW_NOT_FOUND',
    LEGAL_NOT_FOUND: 'SUPPORT.LEGAL_NOT_FOUND',
    UNSUPPORTED_TYPE: 'SUPPORT.UNSUPPORTED_TYPE',
    CREATE_FAILED: 'SUPPORT.CREATE_FAILED',
    UPDATE_FAILED: 'SUPPORT.UPDATE_FAILED',
    DELETE_FAILED: 'SUPPORT.DELETE_FAILED',
    FETCH_FAILED: 'SUPPORT.FETCH_FAILED',
  },

  ADMIN: {
    SUPABASE_ERROR: 'ADMIN.SUPABASE_ERROR',
    CONFIG_NOT_FOUND: 'ADMIN.CONFIG_NOT_FOUND',
    CONFIG_UPDATE_FAILED: 'ADMIN.CONFIG_UPDATE_FAILED',
    THRESHOLD_INVALID: 'ADMIN.THRESHOLD_INVALID',
    STOCK_ERROR: 'ADMIN.STOCK_ERROR',
    UNKNOWN_ACTION: 'ADMIN.UNKNOWN_ACTION',
  },

  SEO: {
    TEMPLATE_NOT_FOUND: 'SEO.TEMPLATE_NOT_FOUND',
    SITEMAP_FETCH_FAILED: 'SEO.SITEMAP_FETCH_FAILED',
    SQL_INJECTION: 'SEO.SQL_INJECTION_BLOCKED',
    MONITORING_ERROR: 'SEO.MONITORING_ERROR',
    GENERATION_FAILED: 'SEO.GENERATION_FAILED',
    AUDIT_FAILED: 'SEO.AUDIT_FAILED',
  },

  SHIPPING: {
    ORDER_NOT_FOUND: 'SHIPPING.ORDER_NOT_FOUND',
    ADDRESS_NOT_FOUND: 'SHIPPING.ADDRESS_NOT_FOUND',
    UPDATE_FAILED: 'SHIPPING.UPDATE_FAILED',
    DATA_FETCH_FAILED: 'SHIPPING.DATA_FETCH_FAILED',
  },

  BLOG: {
    ARTICLE_NOT_FOUND: 'BLOG.ARTICLE_NOT_FOUND',
    UNSUPPORTED_TABLE: 'BLOG.UNSUPPORTED_TABLE',
    FETCH_FAILED: 'BLOG.FETCH_FAILED',
  },

  DATABASE: {
    OPERATION_FAILED: 'DATABASE.OPERATION_FAILED',
    CONNECTION_ERROR: 'DATABASE.CONNECTION_ERROR',
    TIMEOUT: 'DATABASE.TIMEOUT',
    RPC_FAILED: 'DATABASE.RPC_FAILED',
    CONFIG_MISSING: 'DATABASE.CONFIG_MISSING',
  },

  EXTERNAL: {
    SERVICE_ERROR: 'EXTERNAL.SERVICE_ERROR',
    HTTP_ERROR: 'EXTERNAL.HTTP_ERROR',
    TIMEOUT: 'EXTERNAL.TIMEOUT',
    API_KEY_MISSING: 'EXTERNAL.API_KEY_MISSING',
  },

  CONFIG: {
    MISSING: 'CONFIG.MISSING',
    LOAD_FAILED: 'CONFIG.LOAD_FAILED',
    UPDATE_FAILED: 'CONFIG.UPDATE_FAILED',
    ENCRYPT_FAILED: 'CONFIG.ENCRYPT_FAILED',
    DECRYPT_FAILED: 'CONFIG.DECRYPT_FAILED',
  },

  UPLOAD: {
    PROCESSING_FAILED: 'UPLOAD.PROCESSING_FAILED',
    STORAGE_ERROR: 'UPLOAD.STORAGE_ERROR',
    ANALYTICS_FAILED: 'UPLOAD.ANALYTICS_FAILED',
  },

  MESSAGE: {
    NOT_FOUND: 'MESSAGE.NOT_FOUND',
    CREATE_FAILED: 'MESSAGE.CREATE_FAILED',
    UPDATE_FAILED: 'MESSAGE.UPDATE_FAILED',
    FETCH_FAILED: 'MESSAGE.FETCH_FAILED',
  },

  ANALYTICS: {
    CONFIG_NOT_FOUND: 'ANALYTICS.CONFIG_NOT_FOUND',
    METRICS_FAILED: 'ANALYTICS.METRICS_FAILED',
    UPDATE_FAILED: 'ANALYTICS.UPDATE_FAILED',
  },

  VEHICLE: {
    NOT_FOUND: 'VEHICLE.NOT_FOUND',
    BRAND_RPC_FAILED: 'VEHICLE.BRAND_RPC_FAILED',
    INVALID_DATA: 'VEHICLE.INVALID_DATA',
  },

  SEARCH: {
    INDEX_NOT_SUPPORTED: 'SEARCH.INDEX_NOT_SUPPORTED',
    QUERY_FAILED: 'SEARCH.QUERY_FAILED',
    FILTER_FAILED: 'SEARCH.FILTER_FAILED',
  },

  INVOICE: {
    FETCH_FAILED: 'INVOICE.FETCH_FAILED',
  },

  LAYOUT: {
    STATS_FAILED: 'LAYOUT.STATS_FAILED',
    SECTION_NOT_SUPPORTED: 'LAYOUT.SECTION_NOT_SUPPORTED',
    FETCH_FAILED: 'LAYOUT.FETCH_FAILED',
  },

  DASHBOARD: {
    STATS_FAILED: 'DASHBOARD.STATS_FAILED',
  },

  SUPPLIER: {
    FETCH_FAILED: 'SUPPLIER.FETCH_FAILED',
    UPDATE_FAILED: 'SUPPLIER.UPDATE_FAILED',
  },

  PRODUCT: {
    NOT_FOUND: 'PRODUCT.NOT_FOUND',
    PRICING_FAILED: 'PRODUCT.PRICING_FAILED',
  },

  RESOURCE: {
    NOT_FOUND: 'RESOURCE.NOT_FOUND',
    CONFLICT: 'RESOURCE.CONFLICT',
  },

  OPERATION: {
    FAILED: 'OPERATION.FAILED',
  },
} as const;

export type ErrorCode =
  (typeof ErrorCodes)[keyof typeof ErrorCodes][keyof (typeof ErrorCodes)[keyof typeof ErrorCodes]];
