import { z } from "zod";
import { SchemaVersionSchema } from "../shared/schema-version";
import { StatusSchema } from "../shared/status";
import { SourceConfidenceSchema } from "../shared/source-confidence";
import { DomainIdSchema } from "../shared/domain";
import { RiskSchema } from "../shared/risk";
import { DeletePolicySchema } from "../shared/delete-policy";

/**
 * Layer 1 — DB table entry (auto-generated by `scripts/registry/build-db-registry.js`
 * which extends `scripts/audit/build-db-usage-map.js`).
 *
 * Cross-références : `usedBy` liste les callsites code TypeScript (services /
 * controllers / scripts) qui font `supabase.from('<table>')` ou équivalent.
 *
 * @see ADR-058 §Layer 1
 */
const DbColumnSchema = z.object({
  name: z.string().min(1),
  type: z.string().min(1), // PG type string (text, jsonb, integer, …)
  nullable: z.boolean(),
  hasDefault: z.boolean(),
});

const DbIndexSchema = z.object({
  name: z.string().min(1),
  columns: z.array(z.string()).min(1),
  unique: z.boolean().default(false),
});

export const DbTableEntrySchema = z.object({
  schemaVersion: SchemaVersionSchema,
  id: z.string().min(1), // canonical id, e.g. "__seo_gsc_daily"
  name: z.string().min(1),
  schema: z.string().default("public"), // PG schema (typically "public")
  domain: DomainIdSchema,
  status: StatusSchema,
  owner: z.string().min(1),
  sourceConfidence: SourceConfidenceSchema,
  columns: z.array(DbColumnSchema).default([]),
  indexes: z.array(DbIndexSchema).default([]),
  rlsEnabled: z.boolean(),
  usedBy: z.array(z.string()).default([]), // callsites
  inMigrations: z.array(z.string()).default([]), // migration filenames
  deletePolicy: DeletePolicySchema.default("FREE"),
  risk: RiskSchema.default("low"),
});

export type DbTableEntry = z.infer<typeof DbTableEntrySchema>;
