import { z } from "zod";
import { SchemaVersionSchema } from "../shared/schema-version";
import { StatusSchema } from "../shared/status";
import { SourceConfidenceSchema } from "../shared/source-confidence";

/**
 * The three governed dependency buckets a specifier can be declared in.
 * Mirrors `DEPENDENCY_BUCKETS` in `scripts/registry/lib/utils.js` (the L1
 * builder + fidelity validator SoT). Kept as an enum so the atomic
 * `(workspace, declaredIn, bucket, specifier)` tuple is fully typed.
 */
export const DependencyBucketSchema = z.enum([
  "dependencies",
  "devDependencies",
  "peerDependencies",
]);
export type DependencyBucket = z.infer<typeof DependencyBucketSchema>;

/**
 * One atomic declaration of a dependency : a single `(workspace, package.json,
 * bucket, specifier)` tuple, captured at read time by the builder. This is the
 * indivisible unit of provenance — never split into parallel arrays and
 * re-zipped (that lost the pairing; incident: 7/9 `zod` occurrences shipped
 * with a false `declaredIn` in the modernization inventory).
 */
export const DepOccurrenceSchema = z.object({
  workspace: z.string().min(1), // package.json `name` (or path when unnamed)
  declaredIn: z.string().min(1), // exact package.json path the declaration lives in
  bucket: DependencyBucketSchema, // which declaration class it belongs to
  specifier: z.string().min(1), // the raw version range as written in that manifest
});
export type DepOccurrence = z.infer<typeof DepOccurrenceSchema>;

/**
 * Layer 1 — Dependency entry (auto-generated by
 * `scripts/registry/build-deps-registry.js`).
 *
 * Keyed by `id = "<source>:<name>@<specifier>"` (per-specifier, unchanged — the
 * L2 `dep-governance.yaml` overlay and the §4.2 cross-contract test match on
 * this exact id). Provenance is carried by `occurrences[]`, where each element
 * is a fully atomic `(workspace, declaredIn, bucket, specifier)` tuple. Every
 * `occurrence.specifier` equals `version`; `id === depId(name, specifier)`.
 *
 * V1 scope : npm packages externes + cross-workspace internal imports
 * (`@repo/*`, `@fafa/*`, `@monorepo/*`).
 */
export const DepEntrySchema = z.object({
  schemaVersion: SchemaVersionSchema,
  id: z.string().min(1), // canonical id, e.g. "npm:zod@3.25.76" or "workspace:@repo/seo-roles"
  name: z.string().min(1),
  version: z.string().min(1), // == every occurrence.specifier for this entry
  source: z.enum(["npm", "workspace", "github", "git"]),
  occurrences: z.array(DepOccurrenceSchema).min(1), // atomic provenance — never empty
  status: StatusSchema,
  owner: z.string().min(1),
  sourceConfidence: SourceConfidenceSchema,
  // V1.5+ : depcruise boundaries violations would land here
});

export type DepEntry = z.infer<typeof DepEntrySchema>;
