import { z } from "zod";
import { SchemaVersionSchema } from "../shared/schema-version";
import { StatusSchema } from "../shared/status";
import { SourceConfidenceSchema } from "../shared/source-confidence";

/**
 * Layer 1 — Dependency entry (auto-generated by
 * `scripts/registry/build-deps-registry.js`).
 *
 * Source : parse `package.json` workspaces + `.dependency-cruiser.cjs` boundaries
 * + `dep-cruiser` JSON output.
 *
 * V1 scope : npm packages externes + cross-workspace internal imports
 * (`@repo/*`, `@fafa/*`, `@monorepo/*`).
 */
export const DepEntrySchema = z.object({
  schemaVersion: SchemaVersionSchema,
  id: z.string().min(1), // canonical id, e.g. "npm:zod@3.25.76" or "workspace:@repo/seo-roles"
  name: z.string().min(1),
  version: z.string().min(1),
  source: z.enum(["npm", "workspace", "github", "git"]),
  workspaces: z.array(z.string()).default([]), // which workspaces import this dep
  declaredIn: z.array(z.string()).default([]), // package.json paths where declared
  status: StatusSchema,
  owner: z.string().min(1),
  sourceConfidence: SourceConfidenceSchema,
  // V1.5+ : depcruise boundaries violations would land here
});

export type DepEntry = z.infer<typeof DepEntrySchema>;
