import { z } from "zod";
import { SchemaVersionSchema } from "../shared/schema-version";

/**
 * Layer 1 (projection) — Dependency / coordination graph
 * (auto-generated by `scripts/registry/build-dependency-graph.js`).
 *
 * V1 scope (anti-duplication): the PR-stack DAG only. The module import graph
 * already exists (files.json imports/importedBy) and module cycle detection is
 * owned by `npm run audit:madge` — this builder does NOT recompute either.
 * The PR↔module/domain join (needs per-PR changed files) is a documented
 * follow-up, not front-loaded here.
 *
 * Derived purely from planning.json (headRef/baseRef) — no extra `gh` fetch.
 * Like planning.json it is a TIME-VARYING snapshot (meta.generatedAt), kept OUT
 * of the determinism-gated `registry:build` group and gitignored.
 *
 * Purpose: quantify WIP stack saturation for Etape 3 (target maxStackDepth <= 2).
 */
export const DepGraphNodeSchema = z.object({
  id: z.string().min(1), // "pr:601"
  number: z.number().int().positive(),
  headRef: z.string(),
  baseRef: z.string(),
  status: z.string(),
  workType: z.string().nullable(),
  depth: z.number().int().positive(), // 1 = directly on a trunk branch
});

export const DepGraphEdgeSchema = z.object({
  from: z.string().min(1), // child PR id (stacked PR)
  to: z.string().min(1), // parent PR id (its baseRef is the parent's headRef)
  kind: z.literal("stacks-on"),
});

export const DependencyGraphSchema = z.object({
  schemaVersion: SchemaVersionSchema,
  generatedBy: z.string(),
  meta: z.object({
    generatedAt: z.string(),
    source: z.string(), // "planning.json"
    degraded: z.boolean(), // true if planning.json absent/degraded
    prCount: z.number().int().nonnegative(),
  }),
  nodes: z.array(DepGraphNodeSchema),
  edges: z.array(DepGraphEdgeSchema),
  metrics: z.object({
    prCount: z.number().int().nonnegative(),
    stackCount: z.number().int().nonnegative(), // PRs stacked on another PR
    maxStackDepth: z.number().int().nonnegative(),
  }),
  // Ratchet target consumed by the PR-DG-2 gate (baseline-ratchet).
  invariants: z.object({
    maxStackDepth: z.number().int().nonnegative(),
  }),
});

export type DependencyGraph = z.infer<typeof DependencyGraphSchema>;
export type DepGraphNode = z.infer<typeof DepGraphNodeSchema>;
export type DepGraphEdge = z.infer<typeof DepGraphEdgeSchema>;
