import { z } from "zod";
import { SchemaVersionSchema } from "../shared/schema-version";
import { StatusSchema } from "../shared/status";
import { SourceConfidenceSchema } from "../shared/source-confidence";
import { DomainIdSchema } from "../shared/domain";
import { FileKindSchema } from "../shared/kind";
import { RiskSchema } from "../shared/risk";
import { DeletePolicySchema } from "../shared/delete-policy";
import { DerivedFromSchema } from "../shared/derived-from";

/**
 * Layer 1 — File entry (auto-generated by `scripts/registry/build-files-registry.js`
 * which extends `scripts/audit/build-deep-inventory.js`).
 *
 * V1 scope :
 *   - `imports` / `importedBy` use plain string IDs (path or refId).
 *     V1.5 promotes to RefId URN format via `schemaVersion` minor bump.
 *   - No `classificationTrail` — V1.5 audit-log per entry.
 *
 * @see ADR-058 §Layer 1 — Data auto-générée
 */
export const FileEntrySchema = z.object({
  schemaVersion: SchemaVersionSchema,
  id: z.string().min(1),
  path: z.string().min(1),
  domain: DomainIdSchema,
  kind: FileKindSchema,
  status: StatusSchema,
  owner: z.string().min(1), // '__unassigned__' if domain=UNKNOWN
  sourceConfidence: SourceConfidenceSchema,
  runtime: z.boolean(),
  loc: z.number().int().nonnegative(),
  imports: z.array(z.string()).default([]),
  importedBy: z.array(z.string()).default([]),
  derivedFrom: z.array(DerivedFromSchema).default([]),
  deletePolicy: DeletePolicySchema.default("FREE"),
  risk: RiskSchema.default("low"),
});

export type FileEntry = z.infer<typeof FileEntrySchema>;
