import { z } from "zod";
import { SchemaVersionSchema } from "../shared/schema-version";

/**
 * Layer 1 (projection) — Planning entry (auto-generated by
 * `scripts/registry/build-planning-registry.js`).
 *
 * Source : GitHub PRs of the monorepo (`gh pr list`). This is a **time-varying
 * snapshot projection**, NOT a deterministic code projection like
 * files/db/rpc/deps/runtime. It is therefore kept OUT of the determinism-gated
 * `registry:build` group and carries a `meta.generatedAt`.
 *
 * **SoT note** : the canonical source of chantiers/EPICs is the vault
 * MOC-Planning-Live (ADR-053). This file is a monorepo-local PR projection used
 * by the control-plane dashboard + dependency graph. It is subordinate to the
 * vault SoT — `meta.sot` declares this explicitly.
 *
 * V1 scope : open/recent PRs of the monorepo. work_type + priority are read from
 * PR labels (per .spec/00-canon/planning/planning-worktype.yml + planning-priority.yml).
 * The PR↔module/domain join is intentionally deferred to the dependency-graph
 * builder (Etape 2), not front-loaded here.
 */
export const PlanningStatusSchema = z.enum([
  "todo",
  "in-progress",
  "review",
  "blocked",
  "done",
  "cancelled",
]);

export const PlanningPrioritySchema = z.enum([
  "P0",
  "P1",
  "P2",
  "P3",
  "P4",
  "P5",
  "P6",
  "P7",
  "P8",
]);

export const PlanningWorkTypeSchema = z.enum([
  "runtime-critical",
  "emergency",
  "governance",
  "seo-runtime",
  "observability",
  "cleanup",
  "migration",
  "debt",
  "experiment",
]);

export const PlanningEntrySchema = z.object({
  schemaVersion: SchemaVersionSchema,
  id: z.string().min(1), // canonical_id, e.g. "github:ak125/nestjs-remix-monorepo:pr:601"
  itemType: z.literal("PR"), // V1 : PRs only. EPIC/ADR/ROADMAP from vault deferred.
  number: z.number().int().positive(),
  title: z.string(),
  url: z.string().min(1),
  status: PlanningStatusSchema,
  priority: PlanningPrioritySchema, // from P0..P8 label, default P5 (triage)
  workType: PlanningWorkTypeSchema.nullable(), // from label, null if unlabeled
  author: z.string(),
  headRef: z.string(),
  baseRef: z.string(),
  isDraft: z.boolean(),
  isStack: z.boolean(), // baseRef not main/dev → stacked PR
  createdAt: z.string(),
  updatedAt: z.string(),
  ageDays: z.number().int().nonnegative(),
  stalenessDays: z.number().int().nonnegative(), // days since updatedAt (vs snapshot time)
});

export type PlanningEntry = z.infer<typeof PlanningEntrySchema>;

export const PlanningRegistrySchema = z.object({
  schemaVersion: SchemaVersionSchema,
  generatedBy: z.string(),
  meta: z.object({
    generatedAt: z.string(),
    source: z.string(), // "github_pulls"
    sot: z.string(), // pointer to vault MOC-Planning-Live (ADR-053)
    repo: z.string(),
    degraded: z.boolean(), // true if gh fetch failed → empty entries
    prCount: z.number().int().nonnegative(),
  }),
  entries: z.array(PlanningEntrySchema),
});

export type PlanningRegistry = z.infer<typeof PlanningRegistrySchema>;
