import { z } from "zod";
import { SchemaVersionSchema } from "../shared/schema-version";
import { StatusSchema } from "../shared/status";
import { SourceConfidenceSchema } from "../shared/source-confidence";

/**
 * Layer 1 — Runtime entrypoint entry (auto-generated by
 * `scripts/registry/build-runtime-registry.js` which extends
 * `audit/runtime-entrypoints.json`).
 *
 * Captures entrypoints that are loaded by the production runtime :
 *   - NestJS modules / controllers / services on the backend
 *   - Remix routes / loaders / actions on the frontend
 *   - Background workers (BullMQ, cron)
 *   - Migration files (loaded at startup by Supabase migration runner)
 *
 * V1 scope : startup-order DAG modeled via `dependsOn[]` (parsed from
 * `@Module({ imports: [...] })`). Cycle detection happens in
 * `validate-invariants.ts` (invariant V1-4 #3 : no cycle).
 */
export const RuntimeKindSchema = z.enum([
  "nestjs-module",
  "nestjs-controller",
  "nestjs-service",
  "remix-route",
  "remix-loader",
  "remix-action",
  "worker",
  "cron",
  "migration",
  "other",
]);

export const RuntimeEntrySchema = z.object({
  schemaVersion: SchemaVersionSchema,
  id: z.string().min(1), // canonical id, e.g. "backend:AppModule"
  path: z.string().min(1),
  kind: RuntimeKindSchema,
  status: StatusSchema,
  sourceConfidence: SourceConfidenceSchema,
  // Startup-order DAG : list of runtime entry IDs this one depends on
  dependsOn: z.array(z.string()).default([]),
  // For Remix : the route path served (e.g. "/pieces/:slug")
  servesRoute: z.string().optional(),
  // For controllers : HTTP path served
  servesPath: z.string().optional(),
});

export type RuntimeEntry = z.infer<typeof RuntimeEntrySchema>;
export type RuntimeKind = z.infer<typeof RuntimeKindSchema>;
