#!/usr/bin/env bash
# scripts/registry/check-no-manual-edit-generated.sh
#
# Pre-commit guard for `audit/registry/*.json` — Repository Control Plane
# Layer 1 (auto) + Layer 3 (canonical projection) artefacts.
#
# Per ADR-058 + memory feedback_hook_reproducibility_proof_over_env_marker.md :
# REFUSE manual `git add` of these files UNLESS BOTH conditions are true :
#
#   (a) `npm_lifecycle_event` matches `^registry:` — the staging came from
#       an official npm script invocation (set by npm runtime, not forgeable
#       via plain `MY_VAR=1 git add ...`)
#
#   (b) The staged file is REPRODUCIBLE — recompute its hash from current
#       Layer 1+2 sources and compare to the staged hash.
#
# Match (a) + (b) = ALLOW. Mismatch on either = REJECT with clear message.
#
# Why double-check : marker env alone is forgeable. Reproducibility alone
# misses an audit trail of "who/how regenerated it". Combining = defense
# in depth (cf. memory feedback_hook_reproducibility_proof_over_env_marker.md).
#
# Usage (pre-commit only — not designed for ad-hoc use) :
#   ./scripts/registry/check-no-manual-edit-generated.sh
#
# Exit codes :
#   0 — no staged registry files OR all checks pass
#   1 — registry file staged manually (reject)
#   2 — internal error

set -euo pipefail

# Files to protect (Layer 1 auto-generated + Layer 3 projection)
PROTECTED_GLOBS=(
  "audit/registry/*.json"
)

# Collect staged files matching protected globs
STAGED=$(git diff --cached --name-only --diff-filter=ACMR | grep -E '^audit/registry/[a-z]+\.json$' || true)

if [ -z "$STAGED" ]; then
  # Nothing to check
  exit 0
fi

# Check (a) : npm_lifecycle_event provenance
# `npm_lifecycle_event` is set by npm runtime to the script name being run.
# Possible values for our case : `registry:build`, `registry:build:files`,
# `registry:build:canonical`, etc. Not present (or empty) for plain CLI use.
LIFECYCLE="${npm_lifecycle_event:-}"
ALLOW_VIA_NPM=0
case "$LIFECYCLE" in
  registry:*) ALLOW_VIA_NPM=1 ;;
esac

# If lifecycle says no, fail fast with clear message before doing reproducibility work
if [ "$ALLOW_VIA_NPM" -eq 0 ]; then
  cat >&2 <<EOF
ERROR (ADR-058): audit/registry/*.json staged outside an official builder.

The following Layer 1/3 artefacts are staged manually :
$(echo "$STAGED" | sed 's/^/  - /')

These files are GENERATED by the Repository Control Plane builders
(scripts/registry/build-*.js). Per ADR-058 SoT clarification :
  - SoT = couple Layer 1 (auto) + Layer 2 overlay manuel
  - Layer 3 = projection canonique générée — JAMAIS éditer à la main

Fix : run \`npm run registry\` to regenerate, then git add (npm sets
npm_lifecycle_event which this hook checks for provenance).

Manual edit override is not supported — if you need to fix a builder bug,
fix the builder source (scripts/registry/*) and commit that, then rebuild.

See : .spec/00-canon/repository-registry/delete-policy.yaml (ADR_REQUIRED).
EOF
  exit 1
fi

# Check (b) : reproducibility — recompute and compare hashes
#
# We re-run the canonical build to regenerate outputs, then compare each
# staged file's hash to the regenerated version. Mismatch = the staged
# content does not derive from current Layer 1+2 sources → reject.
#
# This is the substantive defense : even if npm_lifecycle_event is forged,
# the file must be hash-equal to a fresh rebuild from current SoT.

echo "[registry-guard] verifying reproducibility of $(echo "$STAGED" | wc -l) staged files..." >&2

# Snapshot the staged content for comparison (don't trust working tree)
TMPDIR=$(mktemp -d -t registry-guard.XXXXXX)
trap 'rm -rf "$TMPDIR"' EXIT

for path in $STAGED; do
  # `git show :<path>` reads the staged version (independent of working tree)
  git show ":$path" > "$TMPDIR/staged-$(basename "$path")" 2>/dev/null || {
    echo "ERROR: cannot read staged version of $path" >&2
    exit 2
  }
done

# Rebuild in a side directory to avoid clobbering working tree
# (alternative : use `--check` mode if builders supported it, but they don't yet)
# For V1 we trust that running registry:build doesn't have side effects beyond
# writing audit/registry/*.json. The reproducibility check compares the freshly
# generated content to the staged content.
#
# WARNING : this guard temporarily overwrites audit/registry/*.json in the
# working tree. If the rebuild produces different content from staged, we
# reject ; otherwise the working tree is identical to staged so no harm done.

if ! npm_lifecycle_event="$LIFECYCLE" npm run registry --silent 2>/dev/null; then
  echo "ERROR: registry rebuild failed during reproducibility check" >&2
  exit 2
fi

FAILED=0
for path in $STAGED; do
  STAGED_HASH=$(sha256sum "$TMPDIR/staged-$(basename "$path")" | cut -d' ' -f1)
  FRESH_HASH=$(sha256sum "$path" | cut -d' ' -f1)
  if [ "$STAGED_HASH" != "$FRESH_HASH" ]; then
    cat >&2 <<EOF
ERROR: $path staged hash != freshly-rebuilt hash.
  staged   : $STAGED_HASH
  rebuilt  : $FRESH_HASH

The staged content is NOT reproducible from current Layer 1 + Layer 2
sources. Either :
  - The builders (scripts/registry/*) have changed since the staged version
    was generated → rerun \`npm run registry\` then git add.
  - You manually edited $path → revert and use the builders instead.
EOF
    FAILED=1
  fi
done

if [ "$FAILED" -ne 0 ]; then
  exit 1
fi

echo "[registry-guard] ✓ all staged registry artefacts are reproducible from current SoT" >&2
exit 0
