#!/usr/bin/env bash
# check-no-direct-rag-knowledge-paths.sh — defense-in-depth complement to
# .ast-grep/rules/no-direct-rag-knowledge-write.yml (PR #286).
#
# Plan v3 §Étape 9 deliverable 3 : refuse any commit whose changes contain a
# literal reference to `automecanik-rag/knowledge/` or
# `/opt/automecanik/rag/knowledge/` in source-code STRINGS (between quotes) of
# the refactored pipeline directories.
#
# Why this exists alongside ast-grep :
#   - ast-grep rule is `severity: warning`. Commits flagged but not blocked.
#   - This script is a blocking gate (exit 1 in pre-commit + CI).
#   - ast-grep matches `kind: string` AST nodes only. This script catches plain
#     text in shell scripts, YAML, and any non-Python file in the same scope.
#
# Scope (matches the ast-grep rule scope — plan v3 §Étape 5 refactored dirs) :
#   scripts/wiki-generators/**
#   scripts/wiki-exports/**
#   scripts/raw-downloaders/**
#
# Out of scope (handled by future plan iterations) :
#   scripts/seo/**, scripts/rag/** (legacy ingester scripts)
#   backend/**, frontend/** (legitimate path comments in code)
#
# Pattern : the literal must appear between quotes (`'`, `"`, or backtick) so
# that documentation comments are not flagged. Same shape as ast-grep
# `kind: string` match, broadened across file types.
#
# Pipeline canon (ADR-031 §D20/D22) :
#   automecanik-raw/  →  scripts/wiki-generators/  →  automecanik-wiki/exports/rag/  →  automecanik-rag/knowledge/
#                                                                                       ^ MIRROR via CI sync,
#                                                                                         never written by hand
#
# Usage :
#   scripts/ci/check-no-direct-rag-knowledge-paths.sh --staged   # pre-commit hook mode
#   scripts/ci/check-no-direct-rag-knowledge-paths.sh --all      # CI mode (full tree scoped)
#
# Exit :
#   0  no violation
#   1  violation found (paths printed to stderr)
#   2  bad usage

set -euo pipefail

mode="${1:-}"
case "${mode}" in
  --staged) ;;
  --all) ;;
  *)
    echo "usage: $0 --staged | --all" >&2
    exit 2
    ;;
esac

# In-scope path prefixes (matches .ast-grep/rules/no-direct-rag-knowledge-write.yml).
in_scope() {
  case "$1" in
    scripts/wiki-generators/*) return 0 ;;
    scripts/wiki-exports/*) return 0 ;;
    scripts/raw-downloaders/*) return 0 ;;
  esac
  return 1
}

# Allowlist within the scope — keep minimal, every entry documented.
is_exempt() {
  local f="$1"
  local base
  base=$(basename "${f}")
  # Tests : filename must START with `test_` or END with `_test.{py,ts,tsx}` /
  # `.test.{py,ts,tsx}`. Anchored on basename to avoid false-positives like
  # `_test_violator.py` matching the loose `*test_*.py` glob.
  case "${base}" in
    test_*.py) return 0 ;;
    *_test.py) return 0 ;;
    *_test.ts|*_test.tsx) return 0 ;;
    *.test.py|*.test.ts|*.test.tsx) return 0 ;;
  esac
  # Fixtures under a `tests/` directory anywhere in the path.
  case "${f}" in
    tests/*|*/tests/*) return 0 ;;
  esac
  return 1
}

# Pattern : literal between quotes (`'`, `"`, or backtick). Mirrors ast-grep's
# `kind: string` semantics for non-Python files. Comments without quotes pass.
# POSIX ERE char class : single quote injected via $'\047' (ANSI-C octal).
# Avoids the \x27 hex escape which is PCRE-only and silently misses single
# quotes under grep -E on stock GNU/BSD grep.
quote_class=$'[\047"`]'
pattern="${quote_class}(automecanik-rag/knowledge/|/opt/automecanik/rag/knowledge/)"

# File extensions where a quoted path is a real anti-pattern.
ext_re='\.(py|ts|tsx|js|mjs|cjs|sh|yml|yaml)$'

# Build candidate file list.
if [[ "${mode}" == "--staged" ]]; then
  candidates=$(git diff --cached --name-only --diff-filter=ACMR | grep -E "${ext_re}" || true)
else
  candidates=$(git ls-files | grep -E "${ext_re}" || true)
fi

[[ -z "${candidates}" ]] && exit 0

violations=()
while IFS= read -r f; do
  [[ -z "${f}" ]] && continue
  in_scope "${f}" || continue
  is_exempt "${f}" && continue
  [[ ! -f "${f}" ]] && continue
  if grep -E -q "${pattern}" -- "${f}"; then
    while IFS= read -r line; do
      violations+=("${f}:${line}")
    done < <(grep -nE "${pattern}" -- "${f}" || true)
  fi
done <<< "${candidates}"

if [[ ${#violations[@]} -gt 0 ]]; then
  {
    echo ""
    echo "ERROR (plan v3 §Étape 9, ADR-031 §D20/D22): direct write reference to automecanik-rag/knowledge/"
    echo ""
    echo "These string literals are forbidden under scripts/{wiki-generators,wiki-exports,raw-downloaders}/"
    echo "because automecanik-rag/knowledge/ is a MIRROR regenerated by the sync workflow from"
    echo "automecanik-wiki/exports/rag/. Writing directly bypasses the canon pipeline."
    echo ""
    echo "Violations :"
    for v in "${violations[@]}"; do
      echo "  ${v}"
    done
    echo ""
    echo "Fix :"
    echo "  - For RAG content production, write to automecanik-wiki/exports/rag/<cat>/."
    echo "  - For tests/fixtures, name the file *_test.py, *.test.ts, or place under tests/."
    echo "  - For sync-only code, route through scripts/rag-sync/ which is exempt."
    echo ""
    echo "Reference :"
    echo "  - .ast-grep/rules/no-direct-rag-knowledge-write.yml (warning-level twin)"
    echo "  - plan v3 : /home/deploy/.claude/plans/je-comprend-rien-a-spicy-reddy.md §Étape 9"
    echo "  - ADR-031 §D20/D22 in governance-vault"
  } >&2
  exit 1
fi

exit 0
