#!/usr/bin/env bash
#
# stop-log-session-suggest.sh — Stop hook for Claude Code (auto-commit mode).
#
# Detects whether the current Claude Code session has produced commits or
# PRs ahead of origin/main on the current branch. If so, the script:
#   1. Appends a deterministic 3-line entry to log.md (suffix " (auto)" so
#      it is visually distinguishable from human-curated entries).
#   2. Stages and commits ONLY log.md with `chore(log): auto session entry`.
#   3. Updates the marker file so a re-fire on the same SHA stays silent.
#
# No JSON output, no Claude involvement, no LLM tokens consumed. Idempotent
# (marker file gates re-trigger). Skill `/log-session` remains available for
# curated manual entries.
#
# Wire-up: .claude/settings.json
#   "Stop": [ { "hooks": [ { "type": "command", "command": "bash ..." } ] } ]
#
# Safe by design:
#   - Only stages log.md ; never touches other files.
#   - Skips on main / master / detached HEAD / no commits.
#   - Skips during rebase / merge / cherry-pick / bisect to avoid colliding
#     with operations the user is steering by hand.
#   - Honours pre-commit hooks (no --no-verify).

set -u

REPO_ROOT="$(git -C "${PWD}" rev-parse --show-toplevel 2>/dev/null || echo /opt/automecanik/app)"
cd "$REPO_ROOT" 2>/dev/null || exit 0

LOG_FILE="${REPO_ROOT}/log.md"
MARKER_DIR="${REPO_ROOT}/.claude/.session-log-state"
mkdir -p "$MARKER_DIR" 2>/dev/null
LAST_SHA_FILE="${MARKER_DIR}/last-suggested-head"
LAST_BRANCH_FILE="${MARKER_DIR}/last-suggested-branch"

# Bail if log.md does not exist (feature not yet shipped on this branch).
[ -f "$LOG_FILE" ] || exit 0

# Bail if a multi-step git operation is in progress.
GIT_DIR="$(git rev-parse --git-dir 2>/dev/null || echo .git)"
for marker in rebase-apply rebase-merge MERGE_HEAD CHERRY_PICK_HEAD BISECT_LOG REVERT_HEAD; do
  [ -e "${GIT_DIR}/${marker}" ] && exit 0
done

current_branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '')"
current_head="$(git rev-parse HEAD 2>/dev/null || echo '')"

# Skip on protected branches / detached HEAD.
case "$current_branch" in
  main|master|HEAD|"") exit 0 ;;
esac

# Look for commits ahead of origin/main on the current branch.
commits_ahead="$(git log origin/main..HEAD --oneline 2>/dev/null | wc -l | tr -d ' ')"
[ "${commits_ahead:-0}" -lt 1 ] && exit 0

# Defence-in-depth against runaway auto-commit chains:
# if the most recent commit is itself an auto-log entry, bail. The marker
# file should already prevent re-fire on the same SHA, but if the hook is
# invoked twice (parallel terminal, harness retry, marker race), this guard
# guarantees we never produce two consecutive `chore(log): auto session
# entry` commits.
last_subject="$(git log -1 --pretty=%s 2>/dev/null || true)"
case "$last_subject" in
  "chore(log): auto session entry"*) exit 0 ;;
esac

# Idempotence: same SHA + same branch → already logged, skip.
last_sha="$(cat "$LAST_SHA_FILE" 2>/dev/null || echo '')"
last_branch="$(cat "$LAST_BRANCH_FILE" 2>/dev/null || echo '')"
if [ "$current_head" = "$last_sha" ] && [ "$current_branch" = "$last_branch" ]; then
  exit 0
fi

# Skip if log.md is currently staged or modified by something else — we
# only auto-commit when log.md is the sole change we will introduce.
if ! git diff --quiet -- "$LOG_FILE" || ! git diff --cached --quiet -- "$LOG_FILE"; then
  exit 0
fi

# Gather facts for the entry.
today="$(date +%F)"
last_commit_subject="$(git log -1 --pretty=%s 2>/dev/null | tr -d '\r' | cut -c1-120)"
short_shas="$(git log origin/main..HEAD --pretty=%h 2>/dev/null | tr '\n' ' ' | sed 's/ *$//')"
plus_n=""
if [ "$commits_ahead" -gt 1 ]; then
  plus_n=" (+$((commits_ahead - 1)) other commit$([ "$((commits_ahead - 1))" -gt 1 ] && echo s))"
fi

pr_number=""
pr_part="aucune"
if command -v gh >/dev/null 2>&1; then
  pr_number="$(gh pr list --head "$current_branch" --state open --json number --jq '.[0].number' 2>/dev/null || true)"
  [ -n "$pr_number" ] && pr_part="#${pr_number}"
fi

# Append deterministic entry. Always one blank line before the H2 heading.
{
  printf '\n## %s — %s (auto)\n\n' "$today" "$current_branch"
  printf -- '- **Branche** : `%s`\n' "$current_branch"
  printf -- '- **Décision** : %s%s\n' "$last_commit_subject" "$plus_n"
  printf -- '- **Sortie** : PR %s | commits %s\n' "$pr_part" "$short_shas"
} >> "$LOG_FILE"

# Stage ONLY log.md and commit.
git add -- "$LOG_FILE" 2>/dev/null

# Use a dedicated commit message. Pre-commit hooks run normally (no bypass).
if git commit -m "chore(log): auto session entry for ${current_branch}" \
              -m "Generated by stop-log-session-suggest.sh after detecting ${commits_ahead} commit(s) ahead of origin/main." \
              --quiet 2>/tmp/.session-log-commit-err; then
  # Update marker with the NEW HEAD (the auto-commit just landed).
  printf '%s\n' "$(git rev-parse HEAD)" > "$LAST_SHA_FILE"
  printf '%s\n' "$current_branch" > "$LAST_BRANCH_FILE"
else
  # Commit failed (probably a pre-commit hook). Roll back the staged change
  # so the user finds a clean working tree, leave a marker so we don't loop.
  git reset HEAD -- "$LOG_FILE" >/dev/null 2>&1
  git checkout -- "$LOG_FILE" >/dev/null 2>&1
  printf '%s\n' "$current_head" > "$LAST_SHA_FILE"
  printf '%s\n' "$current_branch" > "$LAST_BRANCH_FILE"
fi

exit 0
