/**
 * Engine profile derivation + motorisation-specific content dicts.
 *
 * ADR-022 Pilier A — R8 duplicate content fix.
 *
 * ⚠️  AUTO-GENERATED by `scripts/seo/build-engine-profile-from-rag.py`.
 * Content comes from RAG editorial gammes at
 * `/opt/automecanik/rag/knowledge/gammes/*.md` (ADR-015 single source of
 * truth for business content, feedback_rag_vault_always_first.md).
 *
 * To modify content: edit the gamme .md frontmatter (symptoms/role), OR
 * edit PROFILE_GAMME_MAP in the generator script. Re-run the script and
 * commit the diff of this file via PR signed commit (G3).
 */

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

export type Fuel =
  | 'essence'
  | 'diesel'
  | 'hybride_essence'
  | 'hybride_diesel'
  | 'electrique'
  | 'gpl'
  | 'ethanol'
  | 'inconnu';

export type PowerTier =
  | 'p1_mini'
  | 'p2_basse'
  | 'p3_moyenne'
  | 'p4_haute'
  | 'p5_sport'
  | 'p6_tres_haute';

export type EngineProfileKey = `${Fuel}_${PowerTier}`;

// ─────────────────────────────────────────────────────────────────────────────
// Derivation helpers
// ─────────────────────────────────────────────────────────────────────────────

const STRIP_ACCENTS_RE = /[̀-ͯ]/g;

export function normalizeFuel(raw?: string | null): Fuel {
  if (!raw) return 'inconnu';
  const s = raw
    .normalize('NFD')
    .replace(STRIP_ACCENTS_RE, '')
    .toLowerCase()
    .trim();
  if (s.includes('electrique') && s.includes('essence'))
    return 'hybride_essence';
  if (s.includes('electrique') && s.includes('diesel')) return 'hybride_diesel';
  if (s === 'electrique') return 'electrique';
  if (s === 'diesel') return 'diesel';
  if (s === 'essence') return 'essence';
  if (s.includes('gpl') || s.includes('lpg')) return 'gpl';
  if (s.includes('ethanol') || s.includes('e85')) return 'ethanol';
  return 'inconnu';
}

export function derivePowerTier(powerPs: number): PowerTier {
  if (!Number.isFinite(powerPs) || powerPs <= 0) return 'p3_moyenne';
  if (powerPs < 75) return 'p1_mini';
  if (powerPs < 100) return 'p2_basse';
  if (powerPs < 130) return 'p3_moyenne';
  if (powerPs < 170) return 'p4_haute';
  if (powerPs < 230) return 'p5_sport';
  return 'p6_tres_haute';
}

export function deriveEngineProfile(
  fuel?: string | null,
  powerPs?: string | number | null,
): EngineProfileKey {
  const f = normalizeFuel(fuel);
  const ps =
    typeof powerPs === 'number'
      ? powerPs
      : parseInt(String(powerPs || '0'), 10);
  const tier = derivePowerTier(ps);
  return `${f}_${tier}` as EngineProfileKey;
}

export function deriveEuroNorm(
  yearFrom?: string | number | null,
): string | null {
  const y =
    typeof yearFrom === 'number'
      ? yearFrom
      : parseInt(String(yearFrom || '0'), 10);
  if (!Number.isFinite(y) || y <= 1980) return null;
  if (y < 1996) return 'Euro 1';
  if (y < 2000) return 'Euro 2';
  if (y < 2005) return 'Euro 3';
  if (y < 2009) return 'Euro 4';
  if (y < 2014) return 'Euro 5';
  if (y < 2017) return 'Euro 6b';
  if (y < 2020) return 'Euro 6c';
  return 'Euro 6d';
}

// ─────────────────────────────────────────────────────────────────────────────
// Content dicts — RAG-sourced from gammes/*.md (auto-generated)
// ─────────────────────────────────────────────────────────────────────────────

const FALLBACK_ISSUES: readonly string[] = [
  'Filtre à air à remplacer selon kilométrage constructeur',
  'Plaquettes et disques de frein à contrôler tous les 30 000 km',
  'Batterie de démarrage à tester au-delà de 4 ans',
  'Liquide de refroidissement à vérifier annuellement',
  'Amortisseurs à inspecter lors de la révision',
];

export const ENGINE_PROFILE_ISSUES: Partial<
  Record<EngineProfileKey, readonly string[]>
> = {
  // RAG sources : bougie-d-allumage, bobine-d-allumage, alternateur, sonde-lambda, debitmetre-d-air, thermostat
  essence_p1_mini: [
    "Bougie d'allumage : Demarrage difficile ou laborieux, rates moteur a froid ou a l acceleration",
    "Bobine d'allumage : Rate moteur localise sur un cylindre precis, voyant moteur allume code p030x",
    'Alternateur : Voyant batterie allume moteur tournant, batterie qui se decharge malgre les trajets',
    'Sonde lambda : Voyant moteur allume avec codes p0130 a p0167, surconsommation de carburant inexpliquee',
    "Débitmètre d'air : Perte de puissance a l acceleration, surconsommation de carburant importante",
    'Thermostat : Aiguille de temperature dans le rouge rapidement, moteur qui ne chauffe jamais aiguille basse',
  ],
  // RAG sources : bougie-d-allumage, bobine-d-allumage, capteur-vilebrequin, corps-papillon, sonde-lambda, courroie-de-distribution
  essence_p2_basse: [
    "Bougie d'allumage : Demarrage difficile ou laborieux, rates moteur a froid ou a l acceleration",
    "Bobine d'allumage : Rate moteur localise sur un cylindre precis, voyant moteur allume code p030x",
    'Capteur vilebrequin : Moteur ne demarre pas (pas de signal de rotation), calages aleatoires en roulant',
    'Boîtier papillon : Ralenti instable ou irregulier, accelerations saccadees ou a-coups',
    'Sonde lambda : Voyant moteur allume avec codes p0130 a p0167, surconsommation de carburant inexpliquee',
    'Courroie de distribution : Aucun symptome visible courroie casse, echeance kilometrique ou temps depassee',
  ],
  // RAG sources : turbo, bobine-d-allumage, chaine-de-distribution, capteur-vilebrequin, debitmetre-d-air, thermostat
  essence_p3_moyenne: [
    'Turbo : Fumee bleue ou noire excessive a l echappement, sifflement ou bruit metallique du turbo',
    "Bobine d'allumage : Rate moteur localise sur un cylindre precis, voyant moteur allume code p030x",
    'Chaîne de distribution : Bruit de cliquetis metallique au demarrage a froid, claquement qui disparait apres quelques secondes',
    'Capteur vilebrequin : Moteur ne demarre pas (pas de signal de rotation), calages aleatoires en roulant',
    "Débitmètre d'air : Perte de puissance a l acceleration, surconsommation de carburant importante",
    'Thermostat : Aiguille de temperature dans le rouge rapidement, moteur qui ne chauffe jamais aiguille basse',
  ],
  // RAG sources : turbo, bobine-d-allumage, chaine-de-distribution, injecteur, debitmetre-d-air, sonde-lambda
  essence_p4_haute: [
    'Turbo : Fumee bleue ou noire excessive a l echappement, sifflement ou bruit metallique du turbo',
    "Bobine d'allumage : Rate moteur localise sur un cylindre precis, voyant moteur allume code p030x",
    'Chaîne de distribution : Bruit de cliquetis metallique au demarrage a froid, claquement qui disparait apres quelques secondes',
    'Injecteur : Rates d allumage ou rate sur un cylindre, fumee noire ou blanche a l echappement',
    "Débitmètre d'air : Perte de puissance a l acceleration, surconsommation de carburant importante",
    'Sonde lambda : Voyant moteur allume avec codes p0130 a p0167, surconsommation de carburant inexpliquee',
  ],
  // RAG sources : turbo, injecteur, chaine-de-distribution, bobine-d-allumage, volant-moteur, sonde-lambda
  essence_p5_sport: [
    'Turbo : Fumee bleue ou noire excessive a l echappement, sifflement ou bruit metallique du turbo',
    'Injecteur : Rates d allumage ou rate sur un cylindre, fumee noire ou blanche a l echappement',
    'Chaîne de distribution : Bruit de cliquetis metallique au demarrage a froid, claquement qui disparait apres quelques secondes',
    "Bobine d'allumage : Rate moteur localise sur un cylindre precis, voyant moteur allume code p030x",
    'Volant moteur : Bruit de claquement ou cognement au ralenti, vibrations anormales transmises a l habitacle',
    'Sonde lambda : Voyant moteur allume avec codes p0130 a p0167, surconsommation de carburant inexpliquee',
  ],
  // RAG sources : turbo, injecteur, chaine-de-distribution, volant-moteur, capteur-vilebrequin, thermostat
  essence_p6_tres_haute: [
    'Turbo : Fumee bleue ou noire excessive a l echappement, sifflement ou bruit metallique du turbo',
    'Injecteur : Rates d allumage ou rate sur un cylindre, fumee noire ou blanche a l echappement',
    'Chaîne de distribution : Bruit de cliquetis metallique au demarrage a froid, claquement qui disparait apres quelques secondes',
    'Volant moteur : Bruit de claquement ou cognement au ralenti, vibrations anormales transmises a l habitacle',
    'Capteur vilebrequin : Moteur ne demarre pas (pas de signal de rotation), calages aleatoires en roulant',
    'Thermostat : Aiguille de temperature dans le rouge rapidement, moteur qui ne chauffe jamais aiguille basse',
  ],
  // RAG sources : vanne-egr, fap, injecteur, turbo, debitmetre-d-air, pompe-a-vide-de-freinage
  diesel_p1_mini: [
    'Vanne EGR : Perte de puissance a bas et moyen regime, fumee noire a l acceleration',
    'FAP : Voyant filtre particules allume tableau, perte de puissance importante mode degrade',
    'Injecteur : Rates d allumage ou rate sur un cylindre, fumee noire ou blanche a l echappement',
    'Turbo : Fumee bleue ou noire excessive a l echappement, sifflement ou bruit metallique du turbo',
    "Débitmètre d'air : Perte de puissance a l acceleration, surconsommation de carburant importante",
    'Pompe à vide de freinage : Pedale de frein tres dure, assistance au freinage defaillante',
  ],
  // RAG sources : vanne-egr, fap, injecteur, turbo, pompe-a-vide-de-freinage, thermostat
  diesel_p2_basse: [
    'Vanne EGR : Perte de puissance a bas et moyen regime, fumee noire a l acceleration',
    'FAP : Voyant filtre particules allume tableau, perte de puissance importante mode degrade',
    'Injecteur : Rates d allumage ou rate sur un cylindre, fumee noire ou blanche a l echappement',
    'Turbo : Fumee bleue ou noire excessive a l echappement, sifflement ou bruit metallique du turbo',
    'Pompe à vide de freinage : Pedale de frein tres dure, assistance au freinage defaillante',
    'Thermostat : Aiguille de temperature dans le rouge rapidement, moteur qui ne chauffe jamais aiguille basse',
  ],
  // RAG sources : vanne-egr, fap, injecteur, turbo, volant-moteur, debitmetre-d-air
  diesel_p3_moyenne: [
    'Vanne EGR : Perte de puissance a bas et moyen regime, fumee noire a l acceleration',
    'FAP : Voyant filtre particules allume tableau, perte de puissance importante mode degrade',
    'Injecteur : Rates d allumage ou rate sur un cylindre, fumee noire ou blanche a l echappement',
    'Turbo : Fumee bleue ou noire excessive a l echappement, sifflement ou bruit metallique du turbo',
    'Volant moteur : Bruit de claquement ou cognement au ralenti, vibrations anormales transmises a l habitacle',
    "Débitmètre d'air : Perte de puissance a l acceleration, surconsommation de carburant importante",
  ],
  // RAG sources : vanne-egr, fap, injecteur, turbo, volant-moteur, capteur-de-pression-turbo
  diesel_p4_haute: [
    'Vanne EGR : Perte de puissance a bas et moyen regime, fumee noire a l acceleration',
    'FAP : Voyant filtre particules allume tableau, perte de puissance importante mode degrade',
    'Injecteur : Rates d allumage ou rate sur un cylindre, fumee noire ou blanche a l echappement',
    'Turbo : Fumee bleue ou noire excessive a l echappement, sifflement ou bruit metallique du turbo',
    'Volant moteur : Bruit de claquement ou cognement au ralenti, vibrations anormales transmises a l habitacle',
    'Capteur de pression turbo : Voyant moteur allume codes p0234-p0239, mode degrade active puissance reduite',
  ],
  // RAG sources : turbo, injecteur, fap, vanne-egr, volant-moteur, capteur-de-pression-turbo
  diesel_p5_sport: [
    'Turbo : Fumee bleue ou noire excessive a l echappement, sifflement ou bruit metallique du turbo',
    'Injecteur : Rates d allumage ou rate sur un cylindre, fumee noire ou blanche a l echappement',
    'FAP : Voyant filtre particules allume tableau, perte de puissance importante mode degrade',
    'Vanne EGR : Perte de puissance a bas et moyen regime, fumee noire a l acceleration',
    'Volant moteur : Bruit de claquement ou cognement au ralenti, vibrations anormales transmises a l habitacle',
    'Capteur de pression turbo : Voyant moteur allume codes p0234-p0239, mode degrade active puissance reduite',
  ],
  // RAG sources : turbo, injecteur, fap, vanne-egr, volant-moteur, capteur-de-pression-turbo
  diesel_p6_tres_haute: [
    'Turbo : Fumee bleue ou noire excessive a l echappement, sifflement ou bruit metallique du turbo',
    'Injecteur : Rates d allumage ou rate sur un cylindre, fumee noire ou blanche a l echappement',
    'FAP : Voyant filtre particules allume tableau, perte de puissance importante mode degrade',
    'Vanne EGR : Perte de puissance a bas et moyen regime, fumee noire a l acceleration',
    'Volant moteur : Bruit de claquement ou cognement au ralenti, vibrations anormales transmises a l habitacle',
    'Capteur de pression turbo : Voyant moteur allume codes p0234-p0239, mode degrade active puissance reduite',
  ],
  // RAG sources : batterie, alternateur, thermostat, sonde-lambda
  hybride_essence_p3_moyenne: [
    'Batterie : Demarrage lent ou laborieux surtout a froid, voyant batterie allume sur le tableau de bord',
    'Alternateur : Voyant batterie allume moteur tournant, batterie qui se decharge malgre les trajets',
    'Thermostat : Aiguille de temperature dans le rouge rapidement, moteur qui ne chauffe jamais aiguille basse',
    'Sonde lambda : Voyant moteur allume avec codes p0130 a p0167, surconsommation de carburant inexpliquee',
  ],
  // RAG sources : batterie, turbo, alternateur, sonde-lambda, thermostat
  hybride_essence_p5_sport: [
    'Batterie : Demarrage lent ou laborieux surtout a froid, voyant batterie allume sur le tableau de bord',
    'Turbo : Fumee bleue ou noire excessive a l echappement, sifflement ou bruit metallique du turbo',
    'Alternateur : Voyant batterie allume moteur tournant, batterie qui se decharge malgre les trajets',
    'Sonde lambda : Voyant moteur allume avec codes p0130 a p0167, surconsommation de carburant inexpliquee',
    'Thermostat : Aiguille de temperature dans le rouge rapidement, moteur qui ne chauffe jamais aiguille basse',
  ],
  // RAG sources : batterie, alternateur
  electrique_p6_tres_haute: [
    'Batterie : Demarrage lent ou laborieux surtout a froid, voyant batterie allume sur le tableau de bord',
    'Alternateur : Voyant batterie allume moteur tournant, batterie qui se decharge malgre les trajets',
  ],
  // RAG sources : alternateur, thermostat, sonde-lambda, batterie, courroie-de-distribution
  inconnu_p3_moyenne: [
    'Alternateur : Voyant batterie allume moteur tournant, batterie qui se decharge malgre les trajets',
    'Thermostat : Aiguille de temperature dans le rouge rapidement, moteur qui ne chauffe jamais aiguille basse',
    'Sonde lambda : Voyant moteur allume avec codes p0130 a p0167, surconsommation de carburant inexpliquee',
    'Batterie : Demarrage lent ou laborieux surtout a froid, voyant batterie allume sur le tableau de bord',
    'Courroie de distribution : Aucun symptome visible courroie casse, echeance kilometrique ou temps depassee',
  ],
};

export function getEngineProfileIssues(
  profile: EngineProfileKey,
): readonly string[] {
  const direct = ENGINE_PROFILE_ISSUES[profile];
  if (direct) return direct;
  const [fuel, ...tierParts] = profile.split('_');
  const tier = tierParts.join('_') as PowerTier;
  const fallbackFuel: Fuel =
    fuel === 'ethanol' || fuel === 'gpl' ? 'essence' : 'inconnu';
  const fallbackKey = `${fallbackFuel}_${tier}` as EngineProfileKey;
  return (
    ENGINE_PROFILE_ISSUES[fallbackKey] ??
    ENGINE_PROFILE_ISSUES.inconnu_p3_moyenne ??
    FALLBACK_ISSUES
  );
}

export const ENGINE_PROFILE_DESCRIPTIONS: Partial<
  Record<EngineProfileKey, string>
> = {
  essence_p1_mini:
    'Bloc essence atmosphérique 3 ou 4 cylindres à injection multipoint, faible cylindrée adaptée aux trajets urbains.',
  essence_p2_basse:
    'Moteur essence 4 cylindres à injection électronique séquentielle, distribution par courroie crantée ou chaîne.',
  essence_p3_moyenne:
    'Moteur essence turbocompressé de cylindrée moyenne (TCe, THP, TSI), injection directe ou semi-directe.',
  essence_p4_haute:
    'Bloc essence à injection directe haute pression, turbocompresseur, distribution par chaîne et gestion électronique complète.',
  essence_p5_sport:
    'Motorisation sportive suralimentée, injection directe haute pression, culasse multisoupapes, refroidisseur intercooler renforcé.',
  essence_p6_tres_haute:
    'Moteur haute performance multi-turbo ou V6/V8 à injection directe, distribution complexe et lubrification renforcée.',
  diesel_p1_mini:
    'Bloc diesel à common rail, turbocompresseur basse pression, FAP et vanne EGR sur les Euro 4 et suivantes.',
  diesel_p2_basse:
    'Diesel common rail première génération, turbocompresseur à géométrie fixe, FAP catalysé sur certaines déclinaisons.',
  diesel_p3_moyenne:
    'Diesel common rail seconde génération, turbo à géométrie variable (VGT), FAP + gestion électronique EDC.',
  diesel_p4_haute:
    'Diesel à injection piézo haute pression, turbo VGT, post-traitement SCR + AdBlue conformité Euro 6.',
  diesel_p5_sport:
    'Diesel performance bi-turbo séquentiel, injection piézo 2000+ bar, SCR + AdBlue conformité Euro 6d.',
  diesel_p6_tres_haute:
    'Diesel haut de gamme V6 ou V8, turbo compound ou tri-turbo, injection common rail 2500 bar, post-traitement multi-étages.',
  hybride_essence_p3_moyenne:
    'Chaîne de traction hybride essence–électrique, transmission eCVT ou à engrenages planétaires, batterie HV NiMH ou Li-ion.',
  hybride_essence_p5_sport:
    'Hybride essence–électrique haute puissance, moteur thermique turbo associé à générateur-moteur, batterie Li-ion refroidie.',
  electrique_p6_tres_haute:
    'Propulsion 100 % électrique, moteur synchrone à aimants permanents ou asynchrone, batterie lithium-ion haute densité.',
  inconnu_p3_moyenne:
    "Motorisation spécifique à ce modèle — consulter la documentation constructeur pour le type d'injection et de suralimentation.",
};

export function getEngineProfileDescription(profile: EngineProfileKey): string {
  const direct = ENGINE_PROFILE_DESCRIPTIONS[profile];
  if (direct) return direct;
  const [fuel, ...tierParts] = profile.split('_');
  const tier = tierParts.join('_') as PowerTier;
  const fallbackFuel: Fuel =
    fuel === 'ethanol' || fuel === 'gpl' ? 'essence' : 'inconnu';
  const fallbackKey = `${fallbackFuel}_${tier}` as EngineProfileKey;
  return (
    ENGINE_PROFILE_DESCRIPTIONS[fallbackKey] ??
    ENGINE_PROFILE_DESCRIPTIONS.inconnu_p3_moyenne!
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// S_MOTOR_ISSUES opener variations (rotated per typeId, pool size 7 prime).
// Placeholders : {brand} {model} {type} {power} {fuel}
// ─────────────────────────────────────────────────────────────────────────────

export const SEO_R8_MOTOR_ISSUES_OPENERS = [
  "Problèmes techniques récurrents de la motorisation {type} {power} ch {fuel} — vérifiez ces points à l'entretien.",
  'Faiblesses connues de la {brand} {model} {type} ({power} ch) : composants à surveiller en priorité.',
  'Points techniques sensibles de ce bloc {type} {fuel} — liste extraite des retours atelier.',
  "Pannes fréquentes sur la motorisation {type} de {power} ch — à contrôler lors d'un achat d'occasion.",
  'Défaillances typiques de ce moteur {fuel} {power} ch équipant la {brand} {model}.',
  'Avant un achat ou une réparation sur la {brand} {model} {type}, prenez connaissance de ces faiblesses documentées.',
  "Retour d'expérience atelier sur la motorisation {type} {power} ch — points de vigilance.",
] as const;

export const MOTOR_ISSUES_SLOT_OFFSET = 500;
