/**
 * Field Catalog — P1.5 Write Ownership & Collision Guard
 *
 * Single source of truth for field-level write ownership.
 * Every editorially protected DB field has exactly one owner role,
 * one write class, one strategy, and one resource group.
 *
 * Rules:
 *  - No wildcards. Every field is listed explicitly.
 *  - WriteScope is derived automatically via deriveWriteScope().
 *  - The registry MUST NOT duplicate this information manually.
 *
 * @see execution-registry.types.ts for type definitions
 */

import { RoleId } from './role-ids';
import type {
  FieldOwnership,
  WriteScope,
  ResourceGroup,
} from './execution-registry.types';

// ═══════════════════════════════════════════════════════════════════
// FIELD CATALOG
// ═══════════════════════════════════════════════════════════════════

export const FIELD_CATALOG: FieldOwnership[] = [
  // ─────────────────────────────────────────────────────────────────
  // seo_gamme_main  (table: __seo_gamme, owner: R1_ROUTER)
  // ─────────────────────────────────────────────────────────────────
  {
    table: '__seo_gamme',
    field: 'sg_title_draft',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'reject',
    resourceGroup: 'seo_gamme_main',
  },
  {
    table: '__seo_gamme',
    field: 'sg_content_draft',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'reject',
    resourceGroup: 'seo_gamme_main',
  },
  {
    table: '__seo_gamme',
    field: 'sg_descrip_draft',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'reject',
    resourceGroup: 'seo_gamme_main',
  },
  {
    table: '__seo_gamme',
    field: 'sg_draft_source',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'seo_gamme_main',
  },
  {
    table: '__seo_gamme',
    field: 'sg_draft_updated_at',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'seo_gamme_main',
  },
  {
    table: '__seo_gamme',
    field: 'sg_draft_llm_model',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'seo_gamme_main',
  },

  // ─────────────────────────────────────────────────────────────────
  // r1_gamme_slots  (table: __seo_r1_gamme_slots, owner: R1_ROUTER)
  //   Separated from __seo_gamme_purchase_guide (2026-03-17)
  // ─────────────────────────────────────────────────────────────────

  // ── R1 content slots ──
  {
    table: '__seo_r1_gamme_slots',
    field: 'r1s_h1_override',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r1_gamme_slots',
  },
  {
    table: '__seo_r1_gamme_slots',
    field: 'r1s_hero_subtitle',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r1_gamme_slots',
  },
  {
    table: '__seo_r1_gamme_slots',
    field: 'r1s_selector_microcopy',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r1_gamme_slots',
  },
  {
    table: '__seo_r1_gamme_slots',
    field: 'r1s_micro_seo_block',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r1_gamme_slots',
  },
  {
    table: '__seo_r1_gamme_slots',
    field: 'r1s_compatibilities_intro',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r1_gamme_slots',
  },
  {
    table: '__seo_r1_gamme_slots',
    field: 'r1s_equipementiers_line',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r1_gamme_slots',
  },
  {
    table: '__seo_r1_gamme_slots',
    field: 'r1s_family_cross_sell_intro',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r1_gamme_slots',
  },
  {
    table: '__seo_r1_gamme_slots',
    field: 'r1s_interest_nuggets',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r1_gamme_slots',
  },
  {
    table: '__seo_r1_gamme_slots',
    field: 'r1s_serp_variants',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r1_gamme_slots',
  },
  {
    table: '__seo_r1_gamme_slots',
    field: 'r1s_intent_lock',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r1_gamme_slots',
  },
  {
    table: '__seo_r1_gamme_slots',
    field: 'r1s_safe_table_rows',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r1_gamme_slots',
  },
  {
    table: '__seo_r1_gamme_slots',
    field: 'r1s_arg1_title',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r1_gamme_slots',
  },
  {
    table: '__seo_r1_gamme_slots',
    field: 'r1s_arg2_title',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r1_gamme_slots',
  },
  {
    table: '__seo_r1_gamme_slots',
    field: 'r1s_arg3_title',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r1_gamme_slots',
  },
  {
    table: '__seo_r1_gamme_slots',
    field: 'r1s_arg4_title',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r1_gamme_slots',
  },

  // ── R1 metadata slots (gatekeeper output) ──
  {
    table: '__seo_r1_gamme_slots',
    field: 'r1s_gatekeeper_score',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r1_gamme_slots',
  },
  {
    table: '__seo_r1_gamme_slots',
    field: 'r1s_gatekeeper_flags',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r1_gamme_slots',
  },
  {
    table: '__seo_r1_gamme_slots',
    field: 'r1s_gatekeeper_checks',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r1_gamme_slots',
  },

  // ─────────────────────────────────────────────────────────────────
  // purchase_guide_main  (table: __seo_gamme_purchase_guide)
  //   R6_GUIDE_ACHAT owns: buying guide editorial slots
  //   (R1 slots migrated to __seo_r1_gamme_slots — 2026-03-17)
  // ─────────────────────────────────────────────────────────────────

  // ── R6 content slots (buying guide editorial) ──
  {
    table: '__seo_gamme_purchase_guide',
    field: 'sgpg_intro_role',
    ownerRole: RoleId.R6_GUIDE_ACHAT,
    writeClass: 'content',
    writeStrategy: 'merge',
    conflictPolicy: 'hold',
    resourceGroup: 'purchase_guide_main',
  },
  {
    table: '__seo_gamme_purchase_guide',
    field: 'sgpg_how_to_choose',
    ownerRole: RoleId.R6_GUIDE_ACHAT,
    writeClass: 'content',
    writeStrategy: 'merge',
    conflictPolicy: 'hold',
    resourceGroup: 'purchase_guide_main',
  },
  {
    table: '__seo_gamme_purchase_guide',
    field: 'sgpg_risk_explanation',
    ownerRole: RoleId.R6_GUIDE_ACHAT,
    writeClass: 'content',
    writeStrategy: 'merge',
    conflictPolicy: 'hold',
    resourceGroup: 'purchase_guide_main',
  },
  {
    table: '__seo_gamme_purchase_guide',
    field: 'sgpg_risk_consequences',
    ownerRole: RoleId.R6_GUIDE_ACHAT,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'purchase_guide_main',
  },
  {
    table: '__seo_gamme_purchase_guide',
    field: 'sgpg_risk_cost_range',
    ownerRole: RoleId.R6_GUIDE_ACHAT,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'purchase_guide_main',
  },
  {
    table: '__seo_gamme_purchase_guide',
    field: 'sgpg_risk_conclusion',
    ownerRole: RoleId.R6_GUIDE_ACHAT,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'purchase_guide_main',
  },
  {
    table: '__seo_gamme_purchase_guide',
    field: 'sgpg_symptoms',
    ownerRole: RoleId.R6_GUIDE_ACHAT,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'purchase_guide_main',
  },
  {
    table: '__seo_gamme_purchase_guide',
    field: 'sgpg_selection_criteria',
    ownerRole: RoleId.R6_GUIDE_ACHAT,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'purchase_guide_main',
  },
  {
    table: '__seo_gamme_purchase_guide',
    field: 'sgpg_anti_mistakes',
    ownerRole: RoleId.R6_GUIDE_ACHAT,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'purchase_guide_main',
  },
  {
    table: '__seo_gamme_purchase_guide',
    field: 'sgpg_decision_tree',
    ownerRole: RoleId.R6_GUIDE_ACHAT,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'purchase_guide_main',
  },
  {
    table: '__seo_gamme_purchase_guide',
    field: 'sgpg_use_cases',
    ownerRole: RoleId.R6_GUIDE_ACHAT,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'purchase_guide_main',
  },
  {
    table: '__seo_gamme_purchase_guide',
    field: 'sgpg_faq',
    ownerRole: RoleId.R6_GUIDE_ACHAT,
    writeClass: 'content',
    writeStrategy: 'merge',
    conflictPolicy: 'hold',
    resourceGroup: 'purchase_guide_main',
  },
  {
    table: '__seo_gamme_purchase_guide',
    field: 'sgpg_compatibility_axes',
    ownerRole: RoleId.R6_GUIDE_ACHAT,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'purchase_guide_main',
  },
  {
    table: '__seo_gamme_purchase_guide',
    field: 'sgpg_brands_guide',
    ownerRole: RoleId.R6_GUIDE_ACHAT,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'purchase_guide_main',
  },
  {
    table: '__seo_gamme_purchase_guide',
    field: 'sgpg_when_pro',
    ownerRole: RoleId.R6_GUIDE_ACHAT,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'purchase_guide_main',
  },

  // ── R6 metadata slots (provenance) ──
  {
    table: '__seo_gamme_purchase_guide',
    field: 'sgpg_source_type',
    ownerRole: RoleId.R6_GUIDE_ACHAT,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'purchase_guide_main',
  },
  {
    table: '__seo_gamme_purchase_guide',
    field: 'sgpg_source_uri',
    ownerRole: RoleId.R6_GUIDE_ACHAT,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'purchase_guide_main',
  },
  {
    table: '__seo_gamme_purchase_guide',
    field: 'sgpg_source_ref',
    ownerRole: RoleId.R6_GUIDE_ACHAT,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'purchase_guide_main',
  },
  {
    table: '__seo_gamme_purchase_guide',
    field: 'sgpg_source_verified',
    ownerRole: RoleId.R6_GUIDE_ACHAT,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'purchase_guide_main',
  },
  {
    table: '__seo_gamme_purchase_guide',
    field: 'sgpg_source_verified_at',
    ownerRole: RoleId.R6_GUIDE_ACHAT,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'purchase_guide_main',
  },
  {
    table: '__seo_gamme_purchase_guide',
    field: 'sgpg_source_verified_by',
    ownerRole: RoleId.R6_GUIDE_ACHAT,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'purchase_guide_main',
  },

  // ── R6 gatekeeper verdict (mirrors r1s_gatekeeper_* on R1_ROUTER) ──
  {
    table: '__seo_gamme_purchase_guide',
    field: 'sgpg_gatekeeper_score',
    ownerRole: RoleId.R6_GUIDE_ACHAT,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'purchase_guide_main',
  },
  {
    table: '__seo_gamme_purchase_guide',
    field: 'sgpg_gatekeeper_flags',
    ownerRole: RoleId.R6_GUIDE_ACHAT,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'purchase_guide_main',
  },
  {
    table: '__seo_gamme_purchase_guide',
    field: 'sgpg_gatekeeper_checks',
    ownerRole: RoleId.R6_GUIDE_ACHAT,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'purchase_guide_main',
  },

  // ── R6 state slot ──
  {
    table: '__seo_gamme_purchase_guide',
    field: 'sgpg_is_draft',
    ownerRole: RoleId.R6_GUIDE_ACHAT,
    writeClass: 'state',
    writeStrategy: 'state_transition',
    conflictPolicy: 'hold',
    resourceGroup: 'purchase_guide_main',
  },

  // ── R6 page contract metadata ──
  {
    table: '__seo_gamme_purchase_guide',
    field: 'sgpg_page_contract',
    ownerRole: RoleId.R6_GUIDE_ACHAT,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'purchase_guide_main',
  },
  {
    table: '__seo_gamme_purchase_guide',
    field: 'sgpg_visual_plan',
    ownerRole: RoleId.R6_GUIDE_ACHAT,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'purchase_guide_main',
  },
  {
    table: '__seo_gamme_purchase_guide',
    field: 'sgpg_role_version',
    ownerRole: RoleId.R6_GUIDE_ACHAT,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'purchase_guide_main',
  },

  // ─────────────────────────────────────────────────────────────────
  // page_brief_main  (table: __seo_page_brief, owner: R1_ROUTER)
  // ─────────────────────────────────────────────────────────────────
  {
    table: '__seo_page_brief',
    field: 'primary_intent',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'reject',
    resourceGroup: 'page_brief_main',
  },
  {
    table: '__seo_page_brief',
    field: 'secondary_intents',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'reject',
    resourceGroup: 'page_brief_main',
  },
  {
    table: '__seo_page_brief',
    field: 'angles_obligatoires',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'reject',
    resourceGroup: 'page_brief_main',
  },
  {
    table: '__seo_page_brief',
    field: 'forbidden_overlap',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'reject',
    resourceGroup: 'page_brief_main',
  },
  {
    table: '__seo_page_brief',
    field: 'faq_paa',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'reject',
    resourceGroup: 'page_brief_main',
  },
  {
    table: '__seo_page_brief',
    field: 'termes_techniques',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'reject',
    resourceGroup: 'page_brief_main',
  },
  {
    table: '__seo_page_brief',
    field: 'preuves',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'reject',
    resourceGroup: 'page_brief_main',
  },
  {
    table: '__seo_page_brief',
    field: 'keywords_primary',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'reject',
    resourceGroup: 'page_brief_main',
  },
  {
    table: '__seo_page_brief',
    field: 'keywords_secondary',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'reject',
    resourceGroup: 'page_brief_main',
  },
  {
    table: '__seo_page_brief',
    field: 'writing_constraints',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'reject',
    resourceGroup: 'page_brief_main',
  },
  {
    table: '__seo_page_brief',
    field: 'confidence_score',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'page_brief_main',
  },
  {
    table: '__seo_page_brief',
    field: 'coverage_score',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'page_brief_main',
  },
  {
    table: '__seo_page_brief',
    field: 'status',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'state',
    writeStrategy: 'state_transition',
    conflictPolicy: 'hold',
    resourceGroup: 'page_brief_main',
  },
  {
    table: '__seo_page_brief',
    field: 'version',
    ownerRole: RoleId.R1_ROUTER,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'page_brief_main',
  },

  // ─────────────────────────────────────────────────────────────────
  // r3_conseil_section  (table: __seo_gamme_conseil, owner: R3_CONSEILS)
  //   Row-per-section model: each sgc_* row belongs to R3_CONSEILS
  // ─────────────────────────────────────────────────────────────────
  {
    table: '__seo_gamme_conseil',
    field: 'sgc_title',
    ownerRole: RoleId.R3_CONSEILS,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r3_conseil_section',
  },
  {
    table: '__seo_gamme_conseil',
    field: 'sgc_content',
    ownerRole: RoleId.R3_CONSEILS,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r3_conseil_section',
  },
  {
    table: '__seo_gamme_conseil',
    field: 'sgc_section_type',
    ownerRole: RoleId.R3_CONSEILS,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r3_conseil_section',
  },
  {
    table: '__seo_gamme_conseil',
    field: 'sgc_order',
    ownerRole: RoleId.R3_CONSEILS,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r3_conseil_section',
  },
  {
    table: '__seo_gamme_conseil',
    field: 'sgc_quality_score',
    ownerRole: RoleId.R3_CONSEILS,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r3_conseil_section',
  },
  {
    table: '__seo_gamme_conseil',
    field: 'sgc_sources',
    ownerRole: RoleId.R3_CONSEILS,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r3_conseil_section',
  },
  {
    table: '__seo_gamme_conseil',
    field: 'sgc_pack_level',
    ownerRole: RoleId.R3_CONSEILS,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r3_conseil_section',
  },
  {
    table: '__seo_gamme_conseil',
    field: 'sgc_eeat_sources',
    ownerRole: RoleId.R3_CONSEILS,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r3_conseil_section',
  },
  {
    table: '__seo_gamme_conseil',
    field: 'sgc_safety_notes',
    ownerRole: RoleId.R3_CONSEILS,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r3_conseil_section',
  },
  {
    table: '__seo_gamme_conseil',
    field: 'sgc_constructeur_mentions',
    ownerRole: RoleId.R3_CONSEILS,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r3_conseil_section',
  },
  {
    table: '__seo_gamme_conseil',
    field: 'sgc_enriched_by',
    ownerRole: RoleId.R3_CONSEILS,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r3_conseil_section',
  },
  {
    table: '__seo_gamme_conseil',
    field: 'sgc_enriched_at',
    ownerRole: RoleId.R3_CONSEILS,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r3_conseil_section',
  },

  // ─────────────────────────────────────────────────────────────────
  // r4_reference_main  (table: __seo_reference, owner: R4_REFERENCE)
  // ─────────────────────────────────────────────────────────────────
  {
    table: '__seo_reference',
    field: 'title',
    ownerRole: RoleId.R4_REFERENCE,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r4_reference_main',
  },
  {
    table: '__seo_reference',
    field: 'meta_description',
    ownerRole: RoleId.R4_REFERENCE,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r4_reference_main',
  },
  {
    table: '__seo_reference',
    field: 'definition',
    ownerRole: RoleId.R4_REFERENCE,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r4_reference_main',
  },
  {
    table: '__seo_reference',
    field: 'role_mecanique',
    ownerRole: RoleId.R4_REFERENCE,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r4_reference_main',
  },
  {
    table: '__seo_reference',
    field: 'composition',
    ownerRole: RoleId.R4_REFERENCE,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r4_reference_main',
  },
  {
    table: '__seo_reference',
    field: 'confusions_courantes',
    ownerRole: RoleId.R4_REFERENCE,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r4_reference_main',
  },
  {
    table: '__seo_reference',
    field: 'symptomes_associes',
    ownerRole: RoleId.R4_REFERENCE,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r4_reference_main',
  },
  {
    table: '__seo_reference',
    field: 'content_html',
    ownerRole: RoleId.R4_REFERENCE,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r4_reference_main',
  },
  {
    table: '__seo_reference',
    field: 'schema_json',
    ownerRole: RoleId.R4_REFERENCE,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r4_reference_main',
  },
  {
    table: '__seo_reference',
    field: 'related_references',
    ownerRole: RoleId.R4_REFERENCE,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r4_reference_main',
  },
  {
    table: '__seo_reference',
    field: 'role_negatif',
    ownerRole: RoleId.R4_REFERENCE,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r4_reference_main',
  },
  {
    table: '__seo_reference',
    field: 'regles_metier',
    ownerRole: RoleId.R4_REFERENCE,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r4_reference_main',
  },
  {
    table: '__seo_reference',
    field: 'scope_limites',
    ownerRole: RoleId.R4_REFERENCE,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r4_reference_main',
  },
  {
    table: '__seo_reference',
    field: 'takeaways',
    ownerRole: RoleId.R4_REFERENCE,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r4_reference_main',
  },
  {
    table: '__seo_reference',
    field: 'synonyms',
    ownerRole: RoleId.R4_REFERENCE,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r4_reference_main',
  },
  {
    table: '__seo_reference',
    field: 'variants',
    ownerRole: RoleId.R4_REFERENCE,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r4_reference_main',
  },
  {
    table: '__seo_reference',
    field: 'key_specs',
    ownerRole: RoleId.R4_REFERENCE,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r4_reference_main',
  },
  {
    table: '__seo_reference',
    field: 'common_questions',
    ownerRole: RoleId.R4_REFERENCE,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r4_reference_main',
  },
  {
    table: '__seo_reference',
    field: 'contamination_flags',
    ownerRole: RoleId.R4_REFERENCE,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r4_reference_main',
  },
  {
    table: '__seo_reference',
    field: 'section_overrides',
    ownerRole: RoleId.R4_REFERENCE,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r4_reference_main',
  },
  {
    table: '__seo_reference',
    field: 'is_published',
    ownerRole: RoleId.R4_REFERENCE,
    writeClass: 'state',
    writeStrategy: 'state_transition',
    conflictPolicy: 'hold',
    resourceGroup: 'r4_reference_main',
  },

  // ─────────────────────────────────────────────────────────────────
  // r2_product_main  (table: __seo_r2_keyword_plan, owner: R2_PRODUCT)
  //   JSONB columns — each is a structured block, not free text
  // ─────────────────────────────────────────────────────────────────
  {
    table: '__seo_r2_keyword_plan',
    field: 'r2kp_entity_pack',
    ownerRole: RoleId.R2_PRODUCT,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r2_product_main',
  },
  {
    table: '__seo_r2_keyword_plan',
    field: 'r2kp_intent_map',
    ownerRole: RoleId.R2_PRODUCT,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r2_product_main',
  },
  {
    table: '__seo_r2_keyword_plan',
    field: 'r2kp_section_map',
    ownerRole: RoleId.R2_PRODUCT,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r2_product_main',
  },
  {
    table: '__seo_r2_keyword_plan',
    field: 'r2kp_section_content',
    ownerRole: RoleId.R2_PRODUCT,
    writeClass: 'content',
    writeStrategy: 'merge',
    conflictPolicy: 'hold',
    resourceGroup: 'r2_product_main',
  },
  {
    table: '__seo_r2_keyword_plan',
    field: 'r2kp_linking_plan',
    ownerRole: RoleId.R2_PRODUCT,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r2_product_main',
  },
  {
    table: '__seo_r2_keyword_plan',
    field: 'r2kp_schema_hints',
    ownerRole: RoleId.R2_PRODUCT,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r2_product_main',
  },
  {
    table: '__seo_r2_keyword_plan',
    field: 'r2kp_audit_backlog',
    ownerRole: RoleId.R2_PRODUCT,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r2_product_main',
  },
  {
    table: '__seo_r2_keyword_plan',
    field: 'r2kp_micro_specs',
    ownerRole: RoleId.R2_PRODUCT,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r2_product_main',
  },
  {
    table: '__seo_r2_keyword_plan',
    field: 'r2kp_qa_report',
    ownerRole: RoleId.R2_PRODUCT,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r2_product_main',
  },
  {
    table: '__seo_r2_keyword_plan',
    field: 'r2kp_quality_score',
    ownerRole: RoleId.R2_PRODUCT,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r2_product_main',
  },
  {
    table: '__seo_r2_keyword_plan',
    field: 'r2kp_status',
    ownerRole: RoleId.R2_PRODUCT,
    writeClass: 'state',
    writeStrategy: 'state_transition',
    conflictPolicy: 'hold',
    resourceGroup: 'r2_product_main',
  },
  {
    table: '__seo_r2_keyword_plan',
    field: 'r2kp_phase',
    ownerRole: RoleId.R2_PRODUCT,
    writeClass: 'state',
    writeStrategy: 'state_transition',
    conflictPolicy: 'hold',
    resourceGroup: 'r2_product_main',
  },
  {
    table: '__seo_r2_keyword_plan',
    field: 'r2kp_gate_report',
    ownerRole: RoleId.R2_PRODUCT,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r2_product_main',
  },
  {
    table: '__seo_r2_keyword_plan',
    field: 'r2kp_anchor_bank',
    ownerRole: RoleId.R2_PRODUCT,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r2_product_main',
  },
  {
    table: '__seo_r2_keyword_plan',
    field: 'r2kp_snippet_bank',
    ownerRole: RoleId.R2_PRODUCT,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r2_product_main',
  },

  // ─────────────────────────────────────────────────────────────────
  // r5_diagnostic_main  (table: __seo_observable, owner: R5_DIAGNOSTIC)
  // ─────────────────────────────────────────────────────────────────
  {
    table: '__seo_observable',
    field: 'title',
    ownerRole: RoleId.R5_DIAGNOSTIC,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r5_diagnostic_main',
  },
  {
    table: '__seo_observable',
    field: 'meta_description',
    ownerRole: RoleId.R5_DIAGNOSTIC,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r5_diagnostic_main',
  },
  {
    table: '__seo_observable',
    field: 'symptom_description',
    ownerRole: RoleId.R5_DIAGNOSTIC,
    writeClass: 'content',
    writeStrategy: 'merge',
    conflictPolicy: 'hold',
    resourceGroup: 'r5_diagnostic_main',
  },
  {
    table: '__seo_observable',
    field: 'sign_description',
    ownerRole: RoleId.R5_DIAGNOSTIC,
    writeClass: 'content',
    writeStrategy: 'merge',
    conflictPolicy: 'hold',
    resourceGroup: 'r5_diagnostic_main',
  },
  {
    table: '__seo_observable',
    field: 'risk_level',
    ownerRole: RoleId.R5_DIAGNOSTIC,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r5_diagnostic_main',
  },
  {
    table: '__seo_observable',
    field: 'safety_gate',
    ownerRole: RoleId.R5_DIAGNOSTIC,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r5_diagnostic_main',
  },
  {
    table: '__seo_observable',
    field: 'dtc_codes',
    ownerRole: RoleId.R5_DIAGNOSTIC,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r5_diagnostic_main',
  },
  {
    table: '__seo_observable',
    field: 'dtc_descriptions',
    ownerRole: RoleId.R5_DIAGNOSTIC,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r5_diagnostic_main',
  },
  {
    table: '__seo_observable',
    field: 'recommended_actions',
    ownerRole: RoleId.R5_DIAGNOSTIC,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r5_diagnostic_main',
  },
  {
    table: '__seo_observable',
    field: 'related_gammes',
    ownerRole: RoleId.R5_DIAGNOSTIC,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r5_diagnostic_main',
  },
  {
    table: '__seo_observable',
    field: 'related_references',
    ownerRole: RoleId.R5_DIAGNOSTIC,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r5_diagnostic_main',
  },
  {
    table: '__seo_observable',
    field: 'differentiation_checklist',
    ownerRole: RoleId.R5_DIAGNOSTIC,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r5_diagnostic_main',
  },
  {
    table: '__seo_observable',
    field: 'consultation_triggers',
    ownerRole: RoleId.R5_DIAGNOSTIC,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r5_diagnostic_main',
  },
  {
    table: '__seo_observable',
    field: 'do_dont_list',
    ownerRole: RoleId.R5_DIAGNOSTIC,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r5_diagnostic_main',
  },
  {
    table: '__seo_observable',
    field: 'is_published',
    ownerRole: RoleId.R5_DIAGNOSTIC,
    writeClass: 'state',
    writeStrategy: 'state_transition',
    conflictPolicy: 'hold',
    resourceGroup: 'r5_diagnostic_main',
  },
  {
    table: '__seo_observable',
    field: 'schema_org',
    ownerRole: RoleId.R5_DIAGNOSTIC,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r5_diagnostic_main',
  },

  // ─────────────────────────────────────────────────────────────────
  // r8_vehicle_main  (table: __seo_r8_pages, owner: R8_VEHICLE)
  // ─────────────────────────────────────────────────────────────────
  {
    table: '__seo_r8_pages',
    field: 'h1',
    ownerRole: RoleId.R8_VEHICLE,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r8_vehicle_main',
  },
  {
    table: '__seo_r8_pages',
    field: 'meta_title',
    ownerRole: RoleId.R8_VEHICLE,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r8_vehicle_main',
  },
  {
    table: '__seo_r8_pages',
    field: 'meta_description',
    ownerRole: RoleId.R8_VEHICLE,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r8_vehicle_main',
  },
  {
    table: '__seo_r8_pages',
    field: 'content_main',
    ownerRole: RoleId.R8_VEHICLE,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r8_vehicle_main',
  },
  {
    table: '__seo_r8_pages',
    field: 'rendered_json',
    ownerRole: RoleId.R8_VEHICLE,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r8_vehicle_main',
  },
  {
    table: '__seo_r8_pages',
    field: 'block_plan',
    ownerRole: RoleId.R8_VEHICLE,
    writeClass: 'content',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r8_vehicle_main',
  },
  {
    table: '__seo_r8_pages',
    field: 'seo_decision',
    ownerRole: RoleId.R8_VEHICLE,
    writeClass: 'state',
    writeStrategy: 'state_transition',
    conflictPolicy: 'hold',
    resourceGroup: 'r8_vehicle_main',
  },
  {
    table: '__seo_r8_pages',
    field: 'diversity_score',
    ownerRole: RoleId.R8_VEHICLE,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r8_vehicle_main',
  },
  {
    table: '__seo_r8_pages',
    field: 'content_fingerprint',
    ownerRole: RoleId.R8_VEHICLE,
    writeClass: 'metadata',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r8_vehicle_main',
  },
  {
    table: '__seo_r8_pages',
    field: 'sitemap_included',
    ownerRole: RoleId.R8_VEHICLE,
    writeClass: 'derived',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r8_vehicle_main',
  },
  {
    table: '__seo_r8_pages',
    field: 'robots_directive',
    ownerRole: RoleId.R8_VEHICLE,
    writeClass: 'derived',
    writeStrategy: 'replace',
    conflictPolicy: 'hold',
    resourceGroup: 'r8_vehicle_main',
  },
];

// ═══════════════════════════════════════════════════════════════════
// TARGET MAP: ResourceGroup → (table, pkField)
// Single source of truth for routing writes to the correct table.
// ═══════════════════════════════════════════════════════════════════

export interface WriteTarget {
  table: string;
  pkField: string;
}

export const GROUP_TABLE_MAP: Record<string, WriteTarget> = {
  seo_gamme_main: { table: '__seo_gamme', pkField: 'sg_pg_id' },
  r1_gamme_slots: {
    table: '__seo_r1_gamme_slots',
    pkField: 'r1s_pg_id',
  },
  purchase_guide_main: {
    table: '__seo_gamme_purchase_guide',
    pkField: 'sgpg_pg_id',
  },
  page_brief_main: { table: '__seo_page_brief', pkField: 'pg_id' },
  r3_conseil_section: {
    table: '__seo_gamme_conseil',
    pkField: 'sgc_pg_id',
  },
  r2_product_main: {
    table: '__seo_r2_keyword_plan',
    pkField: 'r2kp_id',
  },
  r4_reference_main: { table: '__seo_reference', pkField: 'pg_id' },
  r5_diagnostic_main: { table: '__seo_observable', pkField: 'id' },
  r8_vehicle_main: { table: '__seo_r8_pages', pkField: 'id' },
};

/** Resolve the write target (table + pk) for a given resource group */
export function resolveWriteTarget(group: ResourceGroup): WriteTarget | null {
  return GROUP_TABLE_MAP[group] ?? null;
}

// ═══════════════════════════════════════════════════════════════════
// LOOKUP INDEXES (computed once at module load)
// ═══════════════════════════════════════════════════════════════════

/** Fast lookup: "table.field" → FieldOwnership */
export const FIELD_CATALOG_INDEX = new Map<string, FieldOwnership>(
  FIELD_CATALOG.map((f) => [`${f.table}.${f.field}`, f]),
);

// ═══════════════════════════════════════════════════════════════════
// DERIVATION HELPERS
// ═══════════════════════════════════════════════════════════════════

/**
 * Derive the WriteScope for a given role from the FIELD_CATALOG.
 * This is the ONLY way to compute a WriteScope — the registry
 * MUST NOT contain manually duplicated ownedFields/ownedTables.
 */
export function deriveWriteScope(roleId: RoleId): WriteScope {
  const owned = FIELD_CATALOG.filter((f) => f.ownerRole === roleId);
  const groups = [...new Set(owned.map((f) => f.resourceGroup))];
  const fields = owned.map((f) => f.field);
  const tables = [...new Set(owned.map((f) => f.table))];
  return {
    resourceGroups: groups as ResourceGroup[],
    ownedFields: fields,
    ownedTables: tables,
  };
}

/** All FieldOwnership entries for a given role */
export function getOwnedFields(roleId: RoleId): FieldOwnership[] {
  return FIELD_CATALOG.filter((f) => f.ownerRole === roleId);
}

/** FieldOwnership entries for a given role within a specific resource group */
export function getOwnedFieldsForGroup(
  roleId: RoleId,
  group: ResourceGroup,
): FieldOwnership[] {
  return FIELD_CATALOG.filter(
    (f) => f.ownerRole === roleId && f.resourceGroup === group,
  );
}

/** All FieldOwnership entries belonging to a resource group */
export function getFieldsByGroup(group: ResourceGroup): FieldOwnership[] {
  return FIELD_CATALOG.filter((f) => f.resourceGroup === group);
}
