import { Injectable, Logger } from '@nestjs/common';
import { existsSync, readFileSync } from 'fs';
import { join } from 'path';
import { CacheService } from '../../../cache/cache.service';
import { CommandCenterActionsService } from './command-center-actions.service';
import { type OwnerActionV2 } from './command-center-action-rules/score-action';

/**
 * Read-only reader for the Command Center snapshot
 * (audit/registry/command-center-snapshot.json — generated by
 * scripts/governance/build-command-center-snapshot.js). Powers the
 * `/admin/command-center` cockpit.
 *
 * Mirrors RegistryReaderService (ADR-058): committed JSON read via REGISTRY_DIR,
 * existsSync-guarded, NEVER throws (degraded summary on miss), cache-aside with a
 * short TTL on the degraded path (cache-poisoning guard).
 *
 * The committed snapshot is STRUCTURAL truth only (no wall-clock/git fields). This
 * reader adds the LIVE envelope at request time:
 *   - generated_at / git_sha
 *   - stale_status   (from source_truth.last_verified vs now)
 *   - validation_status (from the validator report counts)
 *   - per-department health_score_current (LIVE caps applied: source stale → 79,
 *     cross-module upstream-unreliable → 69, derived from the chains graph)
 *   - global_status (pessimism verdict + reasons[])
 *
 * Path is env-overridable (`REGISTRY_DIR`); the Docker image sets it to the
 * absolute /app/audit/registry so the cwd=/app/backend trap (start.sh `cd backend`)
 * cannot make the file unresolvable.
 */
@Injectable()
export class CommandCenterReaderService {
  private readonly logger = new Logger(CommandCenterReaderService.name);
  private readonly registryDir =
    process.env.REGISTRY_DIR || join(process.cwd(), 'audit', 'registry');
  // Ancré sur registryDir (<root>/audit/registry → <root>/audit-reports), PAS sur
  // process.cwd() : le backend tourne avec cwd=backend/ (start.sh) où le rapport
  // n'existe pas → validation_status restait UNKNOWN alors que le rapport disait
  // 0 erreur (audit 2026-06-11). Même piège que REGISTRY_DIR en Docker.
  private readonly reportPath = join(
    this.registryDir,
    '..',
    '..',
    'audit-reports',
    'agent-operating-map-report.json',
  );

  private static readonly CACHE_KEY = 'admin:command-center:summary';
  private static readonly TTL_OK = 60;
  private static readonly TTL_DEGRADED = 15; // short TTL — poisoning guard

  // Live health-score cap ceilings (LOCKED rules; structural caps are pre-applied
  // in the snapshot base by the generator — these are the request-time ones).
  private static readonly STALE_CAP = 79;
  private static readonly UPSTREAM_UNRELIABLE_CAP = 69;
  private static readonly STALE_WARNING_DAYS = 7;
  private static readonly STALE_DAYS = 14;

  constructor(
    private readonly cacheService: CacheService,
    private readonly actions: CommandCenterActionsService,
  ) {}

  private readJson<T>(filePath: string): T | null {
    try {
      if (!existsSync(filePath)) return null;
      return JSON.parse(readFileSync(filePath, 'utf-8')) as T;
    } catch (e) {
      this.logger.warn(`[command-center] failed reading ${filePath}: ${e}`);
      return null;
    }
  }

  /** Resolved exposure mode (full / light / disabled). */
  getMode(): CommandCenterMode {
    return resolveCommandCenterMode();
  }

  /** Cache-aside aggregate. Degraded results get a short TTL. Mode-aware key. */
  async getCommandCenter(): Promise<CommandCenterResponse> {
    const mode = resolveCommandCenterMode();
    const cacheKey = `${CommandCenterReaderService.CACHE_KEY}:${mode}`;
    const cached = await this.cacheService.get<CommandCenterResponse>(cacheKey);
    if (cached) return cached;

    const built = this.build();
    let result: CommandCenterResponse;
    if (mode === 'light') {
      result = toLightResponse(built);
    } else {
      const action_queue = built.degraded
        ? []
        : await this.actions.computeActionQueue(
            built.departments,
            built.chains,
            mode,
          );
      // PR-3 boucle OBSERVE : champ additif, full mode + flag ON uniquement.
      const seo_outcomes =
        !built.degraded && mode === 'full' && isSeoOutcomesEnabled()
          ? await this.actions.seoActionOutcomes()
          : null;
      result = { ...built, mode, action_queue, seo_outcomes };
    }
    await this.cacheService.set(
      cacheKey,
      result,
      result.degraded
        ? CommandCenterReaderService.TTL_DEGRADED
        : CommandCenterReaderService.TTL_OK,
    );
    return result;
  }

  private build(): Omit<
    CommandCenterResponse,
    'mode' | 'action_queue' | 'seo_outcomes'
  > {
    const now = new Date();
    const gitSha = process.env.GIT_SHA || process.env.SOURCE_COMMIT || null;
    const snapshot = this.readJson<SnapshotFile>(
      join(this.registryDir, 'command-center-snapshot.json'),
    );

    if (!snapshot) {
      // No silent green: degraded is explicit + pessimistic.
      this.logger.warn(
        `[command-center] snapshot absent at ${this.registryDir}/command-center-snapshot.json — degraded`,
      );
      return {
        degraded: true,
        schema_version: 'command-center.v1',
        source_truth: { canon_path: '', last_verified: null },
        summary: this.emptySummary(),
        executive_kpis: [],
        departments: [],
        capabilities: [],
        chains: [],
        alerts: [],
        owner_actions: [],
        generated_at: now.toISOString(),
        git_sha: gitSha,
        stale_status: 'UNKNOWN',
        validation_status: 'UNKNOWN',
        global_status: {
          level: 'WARNING',
          verdict: 'BLOCKED',
          reasons: [
            'snapshot_unavailable — run `npm run governance:command-center` (and verify the Docker image COPYs audit/registry)',
          ],
        },
      };
    }

    const staleStatus = this.computeStale(
      snapshot.source_truth?.last_verified,
      now,
    );
    const validationStatus = this.computeValidationStatus();

    // chains graph: which upstream departments feed each department, with the
    // upstream's certification (worst-case) — used for the cross-module live cap.
    const deptCert = new Map<string, string>();
    for (const d of snapshot.departments) deptCert.set(d.id, d.certification);
    const riskyUpstream = new Set<string>();
    for (const c of snapshot.chains) {
      const fromCert = deptCert.get(c.from);
      if (fromCert === 'UNKNOWN' || fromCert === 'BROKEN')
        riskyUpstream.add(c.to);
    }

    const departments = snapshot.departments.map((d) => {
      let current = d.health_score_base;
      const liveCaps: string[] = [];
      if (staleStatus === 'STALE') {
        if (current > CommandCenterReaderService.STALE_CAP) {
          current = CommandCenterReaderService.STALE_CAP;
        }
        liveCaps.push('source_stale_max_79');
      }
      if (riskyUpstream.has(d.id)) {
        if (current > CommandCenterReaderService.UPSTREAM_UNRELIABLE_CAP) {
          current = CommandCenterReaderService.UPSTREAM_UNRELIABLE_CAP;
        }
        liveCaps.push('upstream_unreliable_max_69');
      }
      return {
        ...d,
        health_score_current: current,
        live_caps_applied: liveCaps,
      };
    });

    const globalStatus = this.computeGlobalStatus(
      snapshot,
      departments,
      staleStatus,
      validationStatus,
    );

    return {
      degraded: false,
      schema_version: snapshot.schema_version,
      source_truth: snapshot.source_truth,
      summary: snapshot.summary,
      executive_kpis: snapshot.executive_kpis,
      departments,
      capabilities: snapshot.capabilities,
      chains: snapshot.chains,
      alerts: snapshot.alerts,
      owner_actions: snapshot.owner_actions,
      generated_at: now.toISOString(),
      git_sha: gitSha,
      stale_status: staleStatus,
      validation_status: validationStatus,
      global_status: globalStatus,
    };
  }

  private computeStale(
    lastVerified: string | null | undefined,
    now: Date,
  ): StaleStatus {
    if (!lastVerified) return 'UNKNOWN';
    const lv = Date.parse(lastVerified);
    if (Number.isNaN(lv)) return 'UNKNOWN';
    const days = Math.floor((now.getTime() - lv) / 86_400_000);
    if (days <= CommandCenterReaderService.STALE_WARNING_DAYS) return 'FRESH';
    if (days <= CommandCenterReaderService.STALE_DAYS) return 'WARNING';
    return 'STALE';
  }

  private computeValidationStatus(): ValidationStatus {
    const report = this.readJson<{
      counts?: { errors?: number; warns?: number };
    }>(this.reportPath);
    if (!report || !report.counts) return 'UNKNOWN';
    if ((report.counts.errors ?? 0) > 0) return 'STRICT_FAIL';
    if ((report.counts.warns ?? 0) > 0) return 'WARN_ONLY';
    return 'VALIDATED';
  }

  private computeGlobalStatus(
    snapshot: SnapshotFile,
    departments: Array<{
      id: string;
      priority: string | null;
      certification: string;
    }>,
    stale: StaleStatus,
    validation: ValidationStatus,
  ): GlobalStatus {
    const reasons: string[] = [];
    const p0Broken = departments.filter(
      (d) => d.priority === 'P0' && d.certification === 'BROKEN',
    );
    const errorAlerts = snapshot.alerts.filter((a) => a.severity === 'error');

    let level: GlobalStatus['level'] = 'OK';
    let verdict: GlobalStatus['verdict'] = 'OPERATIONAL';

    if (p0Broken.length > 0 || validation === 'STRICT_FAIL') {
      level = 'CRITICAL';
      verdict = 'BLOCKED';
      if (p0Broken.length)
        reasons.push(
          `P0 department(s) broken: ${p0Broken.map((d) => d.id).join(', ')}`,
        );
      if (validation === 'STRICT_FAIL')
        reasons.push('operating-map validation STRICT_FAIL');
    } else if (
      errorAlerts.length > 0 ||
      stale === 'STALE' ||
      snapshot.summary.handoffs_incomplete > 0 ||
      snapshot.summary.capabilities_without_evidence > 0
    ) {
      level = 'WARNING';
      verdict = 'PARTIAL_READY';
      if (errorAlerts.length)
        reasons.push(`${errorAlerts.length} error alert(s)`);
      if (stale === 'STALE') reasons.push('snapshot source stale (>14d)');
      if (snapshot.summary.handoffs_incomplete > 0)
        reasons.push(
          `${snapshot.summary.handoffs_incomplete} incomplete handoff(s)`,
        );
      if (snapshot.summary.capabilities_without_evidence > 0)
        reasons.push(
          `${snapshot.summary.capabilities_without_evidence} capability(ies) without evidence`,
        );
    }
    return { level, verdict, reasons };
  }

  private emptySummary(): SnapshotFile['summary'] {
    return {
      departments_total: 0,
      by_priority: { P0: 0, P1: 0, P2: 0, P3: 0 },
      by_state: { live: 0, partial: 0, dormant: 0, broken: 0, duplicate: 0 },
      capabilities_total: 0,
      capabilities_certified: 0,
      capabilities_without_evidence: 0,
      handoffs_total: 0,
      handoffs_incomplete: 0,
    };
  }
}

// ── Shapes (self-contained, mirrors registry-reader convention) ────────────────
// The authoritative contract is .spec/00-canon/ai-registry/command-center-snapshot.schema.json
// (AJV) + @repo/registry CommandCenterSnapshotSchema (Zod). These loose interfaces
// mirror it for the reader; the frontend imports the Zod types from @repo/registry.

type StaleStatus = 'FRESH' | 'WARNING' | 'STALE' | 'UNKNOWN';
type ValidationStatus = 'VALIDATED' | 'WARN_ONLY' | 'STRICT_FAIL' | 'UNKNOWN';

interface GlobalStatus {
  level: 'OK' | 'WARNING' | 'CRITICAL';
  verdict: 'OPERATIONAL' | 'PARTIAL_READY' | 'BLOCKED';
  reasons: string[];
}

interface SnapshotFile {
  schema_version: string;
  source_truth: { canon_path: string; last_verified: string | null };
  summary: {
    departments_total: number;
    by_priority: Record<string, number>;
    by_state: Record<string, number>;
    capabilities_total: number;
    capabilities_certified: number;
    capabilities_without_evidence: number;
    handoffs_total: number;
    handoffs_incomplete: number;
  };
  executive_kpis: unknown[];
  departments: Array<{
    id: string;
    label: string;
    lead: string;
    priority: string | null;
    kpi_primary: string | null;
    state: string;
    family: string;
    capabilities: string[];
    certification: string;
    health_score_base: number;
    structural_caps_applied: string[];
  }>;
  capabilities: unknown[];
  chains: Array<{
    id: string;
    from: string;
    to: string;
    state: string;
    incomplete: boolean;
  }>;
  alerts: Array<{
    code: string;
    severity: string;
    target_kind: string;
    target_id: string;
    message: string;
  }>;
  owner_actions: unknown[];
}

export type CommandCenterMode = 'full' | 'light' | 'disabled';

/**
 * Exposure mode for the Command Center cockpit (owner decision 2026-06-04):
 * full in DEV/PREPROD, restricted in PROD. Explicit `COMMAND_CENTER_MODE` wins;
 * otherwise SAFE DEFAULT = `disabled` when NODE_ENV=production (PROD), else `full`
 * (DEV runs `development`, PREPROD runs `preprod`). The Docker REGISTRY_DIR fix is
 * independent of this flag and stays active in every environment.
 */
export function resolveCommandCenterMode(): CommandCenterMode {
  const raw = (process.env.COMMAND_CENTER_MODE || '').trim().toLowerCase();
  if (raw === 'full' || raw === 'light' || raw === 'disabled') return raw;
  return process.env.NODE_ENV === 'production' ? 'disabled' : 'full';
}

/**
 * PR-3 boucle OBSERVE — flag du champ additif `seo_outcomes`. Défaut OFF ;
 * **PROD toujours OFF** (mirror resolveOrchestrationMode, ADR-087). Hors-prod,
 * `COMMAND_CENTER_SEO_OUTCOMES=true` explicite requis.
 */
export function isSeoOutcomesEnabled(): boolean {
  if (process.env.NODE_ENV === 'production') return false;
  return (
    (process.env.COMMAND_CENTER_SEO_OUTCOMES || '').trim().toLowerCase() ===
    'true'
  );
}

/**
 * Light projection: top-line health only. Strips ALL internal detail
 * (departments, capabilities, chains, alerts, owner_actions, evidence paths,
 * canon_path, git_sha, global_status.reasons) so PROD can show "is it healthy?"
 * without leaking the agent/department map. `summary` aggregate counts are kept
 * (numbers, no internal identifiers).
 */
function toLightResponse(
  full: Omit<CommandCenterResponse, 'mode' | 'action_queue' | 'seo_outcomes'>,
): CommandCenterResponse {
  return {
    degraded: full.degraded,
    schema_version: full.schema_version,
    source_truth: {
      canon_path: '',
      last_verified: full.source_truth.last_verified,
    },
    summary: full.summary,
    executive_kpis: [],
    departments: [],
    capabilities: [],
    chains: [],
    alerts: [],
    owner_actions: [],
    generated_at: full.generated_at,
    git_sha: null,
    stale_status: full.stale_status,
    validation_status: full.validation_status,
    global_status: {
      level: full.global_status.level,
      verdict: full.global_status.verdict,
      reasons: [],
    },
    mode: 'light',
    action_queue: [],
    seo_outcomes: null,
  };
}

export interface CommandCenterResponse extends Omit<
  SnapshotFile,
  'departments'
> {
  degraded: boolean;
  mode: CommandCenterMode;
  action_queue: OwnerActionV2[];
  /** PR-3 boucle OBSERVE — outcomes SEO (flag COMMAND_CENTER_SEO_OUTCOMES, full mode) ; null sinon. */
  seo_outcomes: Record<string, unknown> | null;
  departments: Array<
    SnapshotFile['departments'][number] & {
      health_score_current: number;
      live_caps_applied: string[];
    }
  >;
  generated_at: string;
  git_sha: string | null;
  stale_status: StaleStatus;
  validation_status: ValidationStatus;
  global_status: GlobalStatus;
}
