#!/usr/bin/env python3
"""
render-proposal — Rend une proposal markdown valide v1.0.0 depuis un SourceMap.

Sortie : `automecanik-wiki/proposals/<slug>.md` UNIQUEMENT.
**Garde-fou strict** : refuse d'écrire dans `automecanik-wiki/wiki/<entity_type>/`
(write canon interdit en Phase A/B initiale — promotion = action humaine séparée).

Validation contre `automecanik-wiki/_meta/schema/frontmatter.schema.json`
avant écriture. Si invalide, sortie 2 et `--out` reste vierge.

Usage:
    render_proposal.py --source-map source_map.yaml \\
                       --wiki-root /opt/automecanik/automecanik-wiki
    render_proposal.py --source-map ... --stdout   # n'écrit pas, affiche
    render_proposal.py --source-map ... --out /custom/path/file.md
"""
from __future__ import annotations

import hashlib
import secrets
import sys
import time
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Any

import click
import yaml

from .models import (
    EntityType,
    ProposalSpec,
    SourceMap,
)


def _uuid_v7() -> str:
    """UUIDv7 manuel (timestamp ms + random). Stable et trié temporellement."""
    ts_ms = int(time.time() * 1000)
    ts_hex = f"{ts_ms:012x}"
    rand = secrets.token_hex(10)
    return f"{ts_hex[:8]}-{ts_hex[8:12]}-7{rand[:3]}-{rand[3:7]}-{rand[7:19]}"


def _render_body(spec: ProposalSpec) -> str:
    """Génère le corps markdown structuré (intro + facts + sources)."""
    lines: list[str] = [f"# {spec.title}", ""]
    if spec.body_md.strip():
        lines.extend([spec.body_md.strip(), ""])

    lines.extend(["## Sources", ""])
    for entry in spec.source_map.entries:
        selector_part = f" (`{entry.selector}`)" if entry.selector else ""
        lines.append(
            f"- [{entry.claim_id}] {entry.url}{selector_part} "
            f"— *{entry.extractor_name.value}* — {entry.extracted_at.isoformat()}"
        )
        lines.append(f"  > {entry.quote_verbatim[:200]}{'…' if len(entry.quote_verbatim) > 200 else ''}")
    lines.append("")
    return "\n".join(lines)


def render_proposal_markdown(spec: ProposalSpec) -> tuple[dict[str, Any], str]:
    """
    Retourne (frontmatter_dict, body_md) sans écriture disque.
    Le frontmatter est conforme schema canon v1.0.0.
    """
    today = date.today().isoformat()
    body = _render_body(spec)
    body_hash = hashlib.sha256(body.encode("utf-8")).hexdigest()

    source_refs = []
    for entry in spec.source_map.entries:
        source_refs.append(
            {
                "kind": "web",
                "url": str(entry.url),
                "selector": entry.selector,
                "extractor": entry.extractor_name.value,
                "captured_at": entry.extracted_at.isoformat(),
                "claim_id": entry.claim_id,
            }
        )

    frontmatter: dict[str, Any] = {
        "schema_version": "1.0.0",
        "id": f"{spec.entity_type.value}:{spec.slug}",
        "entity_type": spec.entity_type.value,
        "slug": spec.slug,
        "title": spec.title,
        "aliases": spec.aliases,
        "lang": spec.lang,
        "created_at": today,
        "updated_at": today,
        "truth_level": spec.truth_level,
        "source_refs": source_refs,
        "provenance": {
            "ingested_by": "script:wiki-promotion/render-proposal@1.0.0",
            "promoted_from": None,
        },
        "lineage_id": _uuid_v7(),
        "parents": [],
        "review_status": "proposed",
        "reviewed_by": None,
        "reviewed_at": None,
        "review_notes": (
            "Generated by wiki-promotion pipeline PR-3a (ADR-059 Phase B).\n"
            f"Source extraction methods: {sorted({e.extractor_name.value for e in spec.source_map.entries})}.\n"
            f"Body content hash: sha256:{body_hash}.\n"
            "Awaiting human review before promotion to wiki/<entity_type>/."
        ),
        "exportable": False,
    }

    return frontmatter, body


def _format_md(frontmatter: dict[str, Any], body: str) -> str:
    fm_yaml = yaml.safe_dump(
        frontmatter, allow_unicode=True, sort_keys=False, default_flow_style=False
    )
    return f"---\n{fm_yaml}---\n\n{body}"


def _validate_against_canon(frontmatter: dict[str, Any], schema_path: Path) -> None:
    """Validation jsonschema contre frontmatter.schema.json v1.0.0."""
    if not schema_path.exists():
        click.echo(
            f"WARN: schema canon introuvable: {schema_path}. "
            "Skipping jsonschema validation (pure Pydantic check via ProposalSpec).",
            err=True,
        )
        return
    try:
        import jsonschema  # type: ignore
    except ImportError:
        click.echo(
            "WARN: jsonschema not installed, skipping canon validation. "
            "ProposalSpec Pydantic checks still applied.",
            err=True,
        )
        return
    import json

    schema = json.loads(schema_path.read_text(encoding="utf-8"))
    jsonschema.validate(frontmatter, schema)


def _refuse_wiki_canon_write(out_path: Path, wiki_root: Path) -> None:
    """
    Garde-fou strict : refuse d'écrire dans wiki/<entity_type>/.
    Seuls proposals/ ou paths hors wiki_root sont autorisés.
    """
    try:
        rel = out_path.resolve().relative_to(wiki_root.resolve())
    except ValueError:
        # out_path est hors wiki_root → autorisé (e.g. /tmp/test.md)
        return
    parts = rel.parts
    if len(parts) >= 2 and parts[0] == "wiki" and parts[1] in {e.value for e in EntityType}:
        raise click.ClickException(
            f"refused: writing into wiki canon is forbidden ({out_path}). "
            "render-proposal writes to proposals/ only. Promotion = human action separate."
        )


@click.command()
@click.option(
    "--source-map",
    "source_map_path",
    type=click.Path(exists=True, dir_okay=False, path_type=Path),
    required=True,
    help="Chemin vers le fichier YAML SourceMap (output de build-source-map)",
)
@click.option(
    "--wiki-root",
    type=click.Path(file_okay=False, path_type=Path),
    default=Path("/opt/automecanik/automecanik-wiki"),
    show_default=True,
)
@click.option(
    "--out",
    type=click.Path(dir_okay=False, path_type=Path),
    default=None,
    help="Chemin de sortie. Défaut : <wiki-root>/proposals/<slug>.md",
)
@click.option(
    "--stdout",
    "to_stdout",
    is_flag=True,
    default=False,
    help="Écrit sur stdout, ne touche pas au disque",
)
@click.option(
    "--body-md",
    default="",
    help="Corps markdown additionnel (libre, hors sources auto-générées)",
)
@click.option(
    "--truth-level",
    type=click.Choice(["L0", "L1", "L2", "L3"]),
    default="L1",
    show_default=True,
)
@click.option(
    "--aliases",
    default="",
    help="Aliases comma-séparés (ex: 'C3,C3 II,C3 III')",
)
@click.option(
    "--lang",
    type=click.Choice(["fr", "en"]),
    default="fr",
    show_default=True,
)
def main(
    source_map_path: Path,
    wiki_root: Path,
    out: Path | None,
    to_stdout: bool,
    body_md: str,
    truth_level: str,
    aliases: str,
    lang: str,
) -> None:
    """Rend une proposal markdown v1.0.0 (frontmatter validé canon)."""
    raw = yaml.safe_load(source_map_path.read_text(encoding="utf-8"))
    source_map = SourceMap.model_validate(raw)

    spec = ProposalSpec(
        entity_type=source_map.entity_type,
        slug=source_map.slug,
        title=source_map.title,
        aliases=[a.strip() for a in aliases.split(",") if a.strip()],
        lang=lang,  # type: ignore[arg-type]
        truth_level=truth_level,  # type: ignore[arg-type]
        source_map=source_map,
        body_md=body_md or f"_Proposal généré automatiquement le {datetime.now(timezone.utc).isoformat()} par wiki-promotion PR-3a._",
    )

    frontmatter, body = render_proposal_markdown(spec)
    schema_path = wiki_root / "_meta" / "schema" / "frontmatter.schema.json"
    _validate_against_canon(frontmatter, schema_path)

    markdown = _format_md(frontmatter, body)

    if to_stdout:
        click.echo(markdown, nl=False)
        sys.exit(0)

    if out is None:
        out = wiki_root / "proposals" / f"{spec.slug}.md"

    _refuse_wiki_canon_write(out, wiki_root)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(markdown, encoding="utf-8")
    click.echo(f"wrote {out}")
    sys.exit(0)


if __name__ == "__main__":
    main()
