/**
 * Admin Control Plane — /admin/control-plane
 *
 * Read-only dashboard surfacing the Repository Control Plane (canonical.json,
 * ADR-058) + the planning PR-projection (planning.json, ADR-053). Drives the
 * WIP-reduction work (Etape 3): PR count, zombies (stale > 14d), stacks, and
 * the staleness leaderboard.
 *
 * planning.json is gitignored (generated by `npm run registry:build:planning`),
 * so the WIP section degrades gracefully when the file is absent (e.g. a fresh
 * container) — the repo section (committed canonical.json) always renders.
 */
import { type LoaderFunctionArgs, json, type MetaFunction } from "@remix-run/node";
import { useLoaderData } from "@remix-run/react";
import { type ReactNode } from "react";
import {
  GitPullRequest,
  Skull,
  Layers,
  Boxes,
  ShieldAlert,
  Clock,
  ExternalLink,
  AlertTriangle,
} from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "~/components/ui/alert";
import { Badge } from "~/components/ui/badge";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "~/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "~/components/ui/table";
import { getInternalApiUrlFromRequest } from "~/utils/internal-api.server";
import { logger } from "~/utils/logger";
import { createNoIndexMeta } from "~/utils/meta-helpers";
import { requireAdmin } from "../auth/unified.server";

interface ControlPlaneSummary {
  generatedAt: string;
  degraded: boolean;
  repo: {
    counts: Record<string, number>;
    domainCount: number;
    ownershipGaps: number;
    sotFingerprint: string | null;
  } | null;
  wip: {
    degraded: boolean;
    generatedAt: string | null;
    prCount: number;
    byStatus: Record<string, number>;
    byWorkType: Record<string, number>;
    stacks: number;
    zombies: number;
    topStale: Array<{
      number: number;
      title: string;
      url: string;
      status: string;
      priority: string;
      workType: string | null;
      stalenessDays: number;
      ageDays: number;
      isStack: boolean;
    }>;
  };
}

export const meta: MetaFunction = () => createNoIndexMeta("Control Plane — Admin");

export async function loader({ request, context }: LoaderFunctionArgs) {
  await requireAdmin({ context });

  const res = await fetch(
    getInternalApiUrlFromRequest("/api/admin/control-plane", request),
    {
      headers: {
        "Content-Type": "application/json",
        Cookie: request.headers.get("Cookie") || "",
      },
    },
  );

  if (!res.ok) {
    logger.error(`[control-plane] API ${res.status}`);
    throw new Response("Control Plane API error", { status: res.status });
  }

  const body = (await res.json()) as { data?: ControlPlaneSummary } & ControlPlaneSummary;
  // AdminResponseInterceptor wraps as { success, data, meta }.
  const summary = body.data ?? (body as ControlPlaneSummary);
  return json(summary);
}

function Stat({
  icon,
  label,
  value,
  tone = "default",
}: {
  icon: ReactNode;
  label: string;
  value: number | string;
  tone?: "default" | "warn" | "danger";
}) {
  const toneClass =
    tone === "danger"
      ? "text-red-600"
      : tone === "warn"
        ? "text-amber-600"
        : "text-foreground";
  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
        <CardTitle className="text-sm font-medium text-muted-foreground">
          {label}
        </CardTitle>
        <span className={toneClass}>{icon}</span>
      </CardHeader>
      <CardContent>
        <div className={`text-3xl font-bold ${toneClass}`}>{value}</div>
      </CardContent>
    </Card>
  );
}

export default function AdminControlPlane() {
  const summary = useLoaderData<typeof loader>();
  const { repo, wip } = summary;

  return (
    <div className="space-y-6 p-6">
      <div>
        <h1 className="text-2xl font-bold">Repository Control Plane</h1>
        <p className="text-sm text-muted-foreground">
          Snapshot {new Date(summary.generatedAt).toLocaleString("fr-FR")} ·
          source canonical.json (ADR-058) + planning.json (ADR-053)
        </p>
      </div>

      {wip.degraded ? (
        <Alert>
          <AlertTriangle className="h-4 w-4" />
          <AlertTitle>Données WIP indisponibles</AlertTitle>
          <AlertDescription>
            planning.json absent ou dégradé. Génère-le avec{" "}
            <code>npm run registry:build:planning</code> puis recharge. La vue
            dépôt (canonical.json) reste affichée.
          </AlertDescription>
        </Alert>
      ) : null}

      <section className="space-y-3">
        <h2 className="text-lg font-semibold">WIP (PRs ouvertes)</h2>
        <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
          <Stat icon={<GitPullRequest className="h-4 w-4" />} label="PRs ouvertes" value={wip.prCount} />
          <Stat
            icon={<Skull className="h-4 w-4" />}
            label="Zombies (>14j)"
            value={wip.zombies}
            tone={wip.zombies > 0 ? "danger" : "default"}
          />
          <Stat
            icon={<Layers className="h-4 w-4" />}
            label="Stacks"
            value={wip.stacks}
            tone={wip.stacks > 0 ? "warn" : "default"}
          />
          <Stat
            icon={<Clock className="h-4 w-4" />}
            label="Cible Étape 3"
            value="≤15"
          />
        </div>

        {wip.topStale.length > 0 ? (
          <Card>
            <CardHeader>
              <CardTitle className="text-base">Top staleness</CardTitle>
              <CardDescription>PRs triées par jours sans activité</CardDescription>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>#</TableHead>
                    <TableHead>Titre</TableHead>
                    <TableHead>Statut</TableHead>
                    <TableHead>Type</TableHead>
                    <TableHead className="text-right">Âge (j)</TableHead>
                    <TableHead className="text-right">Stale (j)</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {wip.topStale.map((pr) => (
                    <TableRow key={pr.number}>
                      <TableCell>
                        <a
                          href={pr.url}
                          target="_blank"
                          rel="noreferrer"
                          className="inline-flex items-center gap-1 text-blue-600 hover:underline"
                        >
                          {pr.number}
                          <ExternalLink className="h-3 w-3" />
                        </a>
                      </TableCell>
                      <TableCell className="max-w-md truncate">{pr.title}</TableCell>
                      <TableCell>
                        <Badge variant="outline">{pr.status}</Badge>
                      </TableCell>
                      <TableCell>
                        {pr.workType ? (
                          <Badge variant="secondary">{pr.workType}</Badge>
                        ) : (
                          <span className="text-muted-foreground">—</span>
                        )}
                      </TableCell>
                      <TableCell className="text-right">{pr.ageDays}</TableCell>
                      <TableCell
                        className={`text-right ${pr.stalenessDays > 14 ? "font-semibold text-red-600" : ""}`}
                      >
                        {pr.stalenessDays}
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        ) : null}
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold">Dépôt (canonical.json)</h2>
        {repo ? (
          <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
            <Stat icon={<Boxes className="h-4 w-4" />} label="Domaines" value={repo.domainCount} />
            <Stat
              icon={<ShieldAlert className="h-4 w-4" />}
              label="Ownership gaps"
              value={repo.ownershipGaps}
              tone={repo.ownershipGaps > 0 ? "warn" : "default"}
            />
            {Object.entries(repo.counts).map(([kind, n]) => (
              <Stat key={kind} icon={<Boxes className="h-4 w-4" />} label={kind} value={n} />
            ))}
          </div>
        ) : (
          <Alert>
            <AlertTriangle className="h-4 w-4" />
            <AlertTitle>canonical.json introuvable</AlertTitle>
            <AlertDescription>
              Le registre Repository Control Plane n'a pas pu être lu.
            </AlertDescription>
          </Alert>
        )}
      </section>
    </div>
  );
}
